# nginx.conf - Acces Campus
# nginx fait deux choses :
#   1. Sert les fichiers HTML/CSS/JS du frontend
#   2. Redirige les appels /psw/* vers json-server (port 3001)
# Après chaque modification : nginx.exe -s reload

worker_processes 1;

events {
    # Nombre max de connexions simultanées
    worker_connections 1024;
}

http {

    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen      80;
        server_name localhost;

        # Dossier contenant index.html, app.js, style.css
        root  "C:/nginx/html/acces-campus";
        index index.html;

        # Toute URL inconnue renvoie index.html 
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
