/**
 *
 *  AbsenceCours.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "AbsenceCours.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::ProjetV1;

const std::string AbsenceCours::Cols::_id_absence = "\"id_absence\"";
const std::string AbsenceCours::Cols::_uuid_user = "\"uuid_user\"";
const std::vector<std::string> AbsenceCours::primaryKeyName = {"id_absence","uuid_user"};
const bool AbsenceCours::hasPrimaryKey = true;
const std::string AbsenceCours::tableName = "\"absence_cours\"";

const std::vector<typename AbsenceCours::MetaData> AbsenceCours::metaData_={
{"id_absence","int32_t","integer",4,0,1,1},
{"uuid_user","std::string","uuid",0,0,1,1}
};
const std::string &AbsenceCours::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
AbsenceCours::AbsenceCours(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id_absence"].isNull())
        {
            idAbsence_=std::make_shared<int32_t>(r["id_absence"].as<int32_t>());
        }
        if(!r["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(r["uuid_user"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            idAbsence_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            uuidUser_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

AbsenceCours::AbsenceCours(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idAbsence_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

AbsenceCours::AbsenceCours(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_absence"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id_absence"].isNull())
        {
            idAbsence_=std::make_shared<int32_t>((int32_t)pJson["id_absence"].asInt64());
        }
    }
    if(pJson.isMember("uuid_user"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson["uuid_user"].asString());
        }
    }
}

void AbsenceCours::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idAbsence_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

void AbsenceCours::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_absence"))
    {
        if(!pJson["id_absence"].isNull())
        {
            idAbsence_=std::make_shared<int32_t>((int32_t)pJson["id_absence"].asInt64());
        }
    }
    if(pJson.isMember("uuid_user"))
    {
        if(!pJson["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson["uuid_user"].asString());
        }
    }
}

const int32_t &AbsenceCours::getValueOfIdAbsence() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idAbsence_)
        return *idAbsence_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &AbsenceCours::getIdAbsence() const noexcept
{
    return idAbsence_;
}
void AbsenceCours::setIdAbsence(const int32_t &pIdAbsence) noexcept
{
    idAbsence_ = std::make_shared<int32_t>(pIdAbsence);
    dirtyFlag_[0] = true;
}

const std::string &AbsenceCours::getValueOfUuidUser() const noexcept
{
    static const std::string defaultValue = std::string();
    if(uuidUser_)
        return *uuidUser_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AbsenceCours::getUuidUser() const noexcept
{
    return uuidUser_;
}
void AbsenceCours::setUuidUser(const std::string &pUuidUser) noexcept
{
    uuidUser_ = std::make_shared<std::string>(pUuidUser);
    dirtyFlag_[1] = true;
}
void AbsenceCours::setUuidUser(std::string &&pUuidUser) noexcept
{
    uuidUser_ = std::make_shared<std::string>(std::move(pUuidUser));
    dirtyFlag_[1] = true;
}

void AbsenceCours::updateId(const uint64_t id)
{
}
typename AbsenceCours::PrimaryKeyType AbsenceCours::getPrimaryKey() const
{
    return std::make_tuple(*idAbsence_,*uuidUser_);
}

const std::vector<std::string> &AbsenceCours::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id_absence",
        "uuid_user"
    };
    return inCols;
}

void AbsenceCours::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getIdAbsence())
        {
            binder << getValueOfIdAbsence();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUuidUser())
        {
            binder << getValueOfUuidUser();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> AbsenceCours::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void AbsenceCours::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getIdAbsence())
        {
            binder << getValueOfIdAbsence();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUuidUser())
        {
            binder << getValueOfUuidUser();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value AbsenceCours::toJson() const
{
    Json::Value ret;
    if(getIdAbsence())
    {
        ret["id_absence"]=getValueOfIdAbsence();
    }
    else
    {
        ret["id_absence"]=Json::Value();
    }
    if(getUuidUser())
    {
        ret["uuid_user"]=getValueOfUuidUser();
    }
    else
    {
        ret["uuid_user"]=Json::Value();
    }
    return ret;
}

std::string AbsenceCours::toString() const
{
    return toJson().toStyledString();
}

Json::Value AbsenceCours::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getIdAbsence())
            {
                ret[pMasqueradingVector[0]]=getValueOfIdAbsence();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUuidUser())
            {
                ret[pMasqueradingVector[1]]=getValueOfUuidUser();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getIdAbsence())
    {
        ret["id_absence"]=getValueOfIdAbsence();
    }
    else
    {
        ret["id_absence"]=Json::Value();
    }
    if(getUuidUser())
    {
        ret["uuid_user"]=getValueOfUuidUser();
    }
    else
    {
        ret["uuid_user"]=Json::Value();
    }
    return ret;
}

bool AbsenceCours::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_absence"))
    {
        if(!validJsonOfField(0, "id_absence", pJson["id_absence"], err, true))
            return false;
    }
    else
    {
        err="The id_absence column cannot be null";
        return false;
    }
    if(pJson.isMember("uuid_user"))
    {
        if(!validJsonOfField(1, "uuid_user", pJson["uuid_user"], err, true))
            return false;
    }
    else
    {
        err="The uuid_user column cannot be null";
        return false;
    }
    return true;
}
bool AbsenceCours::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AbsenceCours::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_absence"))
    {
        if(!validJsonOfField(0, "id_absence", pJson["id_absence"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("uuid_user"))
    {
        if(!validJsonOfField(1, "uuid_user", pJson["uuid_user"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool AbsenceCours::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AbsenceCours::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
