/**
 *
 *  Badge.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Badge.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::ProjetV1;

const std::string Badge::Cols::_uuid_badge = "\"uuid_badge\"";
const std::string Badge::Cols::_uuid_user = "\"uuid_user\"";
const std::string Badge::Cols::_date_creation = "\"date_creation\"";
const std::string Badge::primaryKeyName = "uuid_badge";
const bool Badge::hasPrimaryKey = true;
const std::string Badge::tableName = "\"badge\"";

const std::vector<typename Badge::MetaData> Badge::metaData_={
{"uuid_badge","int32_t","integer",4,0,1,1},
{"uuid_user","std::string","uuid",0,0,0,1},
{"date_creation","::trantor::Date","timestamp without time zone",0,0,0,1}
};
const std::string &Badge::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Badge::Badge(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["uuid_badge"].isNull())
        {
            uuidBadge_=std::make_shared<int32_t>(r["uuid_badge"].as<int32_t>());
        }
        if(!r["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(r["uuid_user"].as<std::string>());
        }
        if(!r["date_creation"].isNull())
        {
            auto timeStr = r["date_creation"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateCreation_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            uuidBadge_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            uuidUser_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateCreation_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

Badge::Badge(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            uuidBadge_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateCreation_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

Badge::Badge(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("uuid_badge"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["uuid_badge"].isNull())
        {
            uuidBadge_=std::make_shared<int32_t>((int32_t)pJson["uuid_badge"].asInt64());
        }
    }
    if(pJson.isMember("uuid_user"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson["uuid_user"].asString());
        }
    }
    if(pJson.isMember("date_creation"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["date_creation"].isNull())
        {
            auto timeStr = pJson["date_creation"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateCreation_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Badge::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            uuidBadge_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateCreation_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Badge::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("uuid_badge"))
    {
        if(!pJson["uuid_badge"].isNull())
        {
            uuidBadge_=std::make_shared<int32_t>((int32_t)pJson["uuid_badge"].asInt64());
        }
    }
    if(pJson.isMember("uuid_user"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson["uuid_user"].asString());
        }
    }
    if(pJson.isMember("date_creation"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["date_creation"].isNull())
        {
            auto timeStr = pJson["date_creation"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateCreation_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &Badge::getValueOfUuidBadge() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(uuidBadge_)
        return *uuidBadge_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Badge::getUuidBadge() const noexcept
{
    return uuidBadge_;
}
void Badge::setUuidBadge(const int32_t &pUuidBadge) noexcept
{
    uuidBadge_ = std::make_shared<int32_t>(pUuidBadge);
    dirtyFlag_[0] = true;
}
const typename Badge::PrimaryKeyType & Badge::getPrimaryKey() const
{
    assert(uuidBadge_);
    return *uuidBadge_;
}

const std::string &Badge::getValueOfUuidUser() const noexcept
{
    static const std::string defaultValue = std::string();
    if(uuidUser_)
        return *uuidUser_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Badge::getUuidUser() const noexcept
{
    return uuidUser_;
}
void Badge::setUuidUser(const std::string &pUuidUser) noexcept
{
    uuidUser_ = std::make_shared<std::string>(pUuidUser);
    dirtyFlag_[1] = true;
}
void Badge::setUuidUser(std::string &&pUuidUser) noexcept
{
    uuidUser_ = std::make_shared<std::string>(std::move(pUuidUser));
    dirtyFlag_[1] = true;
}

const ::trantor::Date &Badge::getValueOfDateCreation() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(dateCreation_)
        return *dateCreation_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Badge::getDateCreation() const noexcept
{
    return dateCreation_;
}
void Badge::setDateCreation(const ::trantor::Date &pDateCreation) noexcept
{
    dateCreation_ = std::make_shared<::trantor::Date>(pDateCreation);
    dirtyFlag_[2] = true;
}

void Badge::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Badge::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "uuid_badge",
        "uuid_user",
        "date_creation"
    };
    return inCols;
}

void Badge::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUuidBadge())
        {
            binder << getValueOfUuidBadge();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUuidUser())
        {
            binder << getValueOfUuidUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDateCreation())
        {
            binder << getValueOfDateCreation();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Badge::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void Badge::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUuidBadge())
        {
            binder << getValueOfUuidBadge();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUuidUser())
        {
            binder << getValueOfUuidUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDateCreation())
        {
            binder << getValueOfDateCreation();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Badge::toJson() const
{
    Json::Value ret;
    if(getUuidBadge())
    {
        ret["uuid_badge"]=getValueOfUuidBadge();
    }
    else
    {
        ret["uuid_badge"]=Json::Value();
    }
    if(getUuidUser())
    {
        ret["uuid_user"]=getValueOfUuidUser();
    }
    else
    {
        ret["uuid_user"]=Json::Value();
    }
    if(getDateCreation())
    {
        ret["date_creation"]=getDateCreation()->toDbStringLocal();
    }
    else
    {
        ret["date_creation"]=Json::Value();
    }
    return ret;
}

std::string Badge::toString() const
{
    return toJson().toStyledString();
}

Json::Value Badge::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getUuidBadge())
            {
                ret[pMasqueradingVector[0]]=getValueOfUuidBadge();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUuidUser())
            {
                ret[pMasqueradingVector[1]]=getValueOfUuidUser();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDateCreation())
            {
                ret[pMasqueradingVector[2]]=getDateCreation()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getUuidBadge())
    {
        ret["uuid_badge"]=getValueOfUuidBadge();
    }
    else
    {
        ret["uuid_badge"]=Json::Value();
    }
    if(getUuidUser())
    {
        ret["uuid_user"]=getValueOfUuidUser();
    }
    else
    {
        ret["uuid_user"]=Json::Value();
    }
    if(getDateCreation())
    {
        ret["date_creation"]=getDateCreation()->toDbStringLocal();
    }
    else
    {
        ret["date_creation"]=Json::Value();
    }
    return ret;
}

bool Badge::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("uuid_badge"))
    {
        if(!validJsonOfField(0, "uuid_badge", pJson["uuid_badge"], err, true))
            return false;
    }
    else
    {
        err="The uuid_badge column cannot be null";
        return false;
    }
    if(pJson.isMember("uuid_user"))
    {
        if(!validJsonOfField(1, "uuid_user", pJson["uuid_user"], err, true))
            return false;
    }
    else
    {
        err="The uuid_user column cannot be null";
        return false;
    }
    if(pJson.isMember("date_creation"))
    {
        if(!validJsonOfField(2, "date_creation", pJson["date_creation"], err, true))
            return false;
    }
    return true;
}
bool Badge::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Badge::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("uuid_badge"))
    {
        if(!validJsonOfField(0, "uuid_badge", pJson["uuid_badge"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("uuid_user"))
    {
        if(!validJsonOfField(1, "uuid_user", pJson["uuid_user"], err, false))
            return false;
    }
    if(pJson.isMember("date_creation"))
    {
        if(!validJsonOfField(2, "date_creation", pJson["date_creation"], err, false))
            return false;
    }
    return true;
}
bool Badge::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Badge::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
