/**
 *
 *  Classe.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Classe.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::ProjetV1;

const std::string Classe::Cols::_id_classe = "\"id_classe\"";
const std::string Classe::Cols::_nom_classe = "\"nom_classe\"";
const std::string Classe::primaryKeyName = "id_classe";
const bool Classe::hasPrimaryKey = true;
const std::string Classe::tableName = "\"classe\"";

const std::vector<typename Classe::MetaData> Classe::metaData_={
{"id_classe","int32_t","integer",4,0,1,1},
{"nom_classe","std::string","character varying",0,0,0,1}
};
const std::string &Classe::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Classe::Classe(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id_classe"].isNull())
        {
            idClasse_=std::make_shared<int32_t>(r["id_classe"].as<int32_t>());
        }
        if(!r["nom_classe"].isNull())
        {
            nomClasse_=std::make_shared<std::string>(r["nom_classe"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            idClasse_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            nomClasse_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Classe::Classe(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idClasse_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            nomClasse_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

Classe::Classe(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_classe"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id_classe"].isNull())
        {
            idClasse_=std::make_shared<int32_t>((int32_t)pJson["id_classe"].asInt64());
        }
    }
    if(pJson.isMember("nom_classe"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["nom_classe"].isNull())
        {
            nomClasse_=std::make_shared<std::string>(pJson["nom_classe"].asString());
        }
    }
}

void Classe::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idClasse_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            nomClasse_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

void Classe::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_classe"))
    {
        if(!pJson["id_classe"].isNull())
        {
            idClasse_=std::make_shared<int32_t>((int32_t)pJson["id_classe"].asInt64());
        }
    }
    if(pJson.isMember("nom_classe"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["nom_classe"].isNull())
        {
            nomClasse_=std::make_shared<std::string>(pJson["nom_classe"].asString());
        }
    }
}

const int32_t &Classe::getValueOfIdClasse() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idClasse_)
        return *idClasse_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Classe::getIdClasse() const noexcept
{
    return idClasse_;
}
void Classe::setIdClasse(const int32_t &pIdClasse) noexcept
{
    idClasse_ = std::make_shared<int32_t>(pIdClasse);
    dirtyFlag_[0] = true;
}
const typename Classe::PrimaryKeyType & Classe::getPrimaryKey() const
{
    assert(idClasse_);
    return *idClasse_;
}

const std::string &Classe::getValueOfNomClasse() const noexcept
{
    static const std::string defaultValue = std::string();
    if(nomClasse_)
        return *nomClasse_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Classe::getNomClasse() const noexcept
{
    return nomClasse_;
}
void Classe::setNomClasse(const std::string &pNomClasse) noexcept
{
    nomClasse_ = std::make_shared<std::string>(pNomClasse);
    dirtyFlag_[1] = true;
}
void Classe::setNomClasse(std::string &&pNomClasse) noexcept
{
    nomClasse_ = std::make_shared<std::string>(std::move(pNomClasse));
    dirtyFlag_[1] = true;
}

void Classe::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Classe::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id_classe",
        "nom_classe"
    };
    return inCols;
}

void Classe::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getIdClasse())
        {
            binder << getValueOfIdClasse();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getNomClasse())
        {
            binder << getValueOfNomClasse();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Classe::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void Classe::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getIdClasse())
        {
            binder << getValueOfIdClasse();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getNomClasse())
        {
            binder << getValueOfNomClasse();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Classe::toJson() const
{
    Json::Value ret;
    if(getIdClasse())
    {
        ret["id_classe"]=getValueOfIdClasse();
    }
    else
    {
        ret["id_classe"]=Json::Value();
    }
    if(getNomClasse())
    {
        ret["nom_classe"]=getValueOfNomClasse();
    }
    else
    {
        ret["nom_classe"]=Json::Value();
    }
    return ret;
}

std::string Classe::toString() const
{
    return toJson().toStyledString();
}

Json::Value Classe::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getIdClasse())
            {
                ret[pMasqueradingVector[0]]=getValueOfIdClasse();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getNomClasse())
            {
                ret[pMasqueradingVector[1]]=getValueOfNomClasse();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getIdClasse())
    {
        ret["id_classe"]=getValueOfIdClasse();
    }
    else
    {
        ret["id_classe"]=Json::Value();
    }
    if(getNomClasse())
    {
        ret["nom_classe"]=getValueOfNomClasse();
    }
    else
    {
        ret["nom_classe"]=Json::Value();
    }
    return ret;
}

bool Classe::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_classe"))
    {
        if(!validJsonOfField(0, "id_classe", pJson["id_classe"], err, true))
            return false;
    }
    else
    {
        err="The id_classe column cannot be null";
        return false;
    }
    if(pJson.isMember("nom_classe"))
    {
        if(!validJsonOfField(1, "nom_classe", pJson["nom_classe"], err, true))
            return false;
    }
    else
    {
        err="The nom_classe column cannot be null";
        return false;
    }
    return true;
}
bool Classe::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Classe::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_classe"))
    {
        if(!validJsonOfField(0, "id_classe", pJson["id_classe"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("nom_classe"))
    {
        if(!validJsonOfField(1, "nom_classe", pJson["nom_classe"], err, false))
            return false;
    }
    return true;
}
bool Classe::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Classe::validJsonOfField(size_t index,
                              const std::string &fieldName,
                              const Json::Value &pJson,
                              std::string &err,
                              bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
