/**
 *
 *  Cours.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Cours.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::ProjetV1;

const std::string Cours::Cols::_id_cours = "\"id_cours\"";
const std::string Cours::Cols::_num_salle = "\"num_salle\"";
const std::string Cours::Cols::_heure_debut = "\"heure_debut\"";
const std::string Cours::Cols::_heure_fin = "\"heure_fin\"";
const std::string Cours::Cols::_id_classe = "\"id_classe\"";
const std::string Cours::primaryKeyName = "id_cours";
const bool Cours::hasPrimaryKey = true;
const std::string Cours::tableName = "\"cours\"";

const std::vector<typename Cours::MetaData> Cours::metaData_={
{"id_cours","int32_t","integer",4,1,1,1},
{"num_salle","int32_t","integer",4,0,0,1},
{"heure_debut","std::string","time without time zone",0,0,0,1},
{"heure_fin","std::string","time without time zone",0,0,0,1},
{"id_classe","int32_t","integer",4,0,0,0}
};
const std::string &Cours::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Cours::Cours(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id_cours"].isNull())
        {
            idCours_=std::make_shared<int32_t>(r["id_cours"].as<int32_t>());
        }
        if(!r["num_salle"].isNull())
        {
            numSalle_=std::make_shared<int32_t>(r["num_salle"].as<int32_t>());
        }
        if(!r["heure_debut"].isNull())
        {
            heureDebut_=std::make_shared<std::string>(r["heure_debut"].as<std::string>());
        }
        if(!r["heure_fin"].isNull())
        {
            heureFin_=std::make_shared<std::string>(r["heure_fin"].as<std::string>());
        }
        if(!r["id_classe"].isNull())
        {
            idClasse_=std::make_shared<int32_t>(r["id_classe"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            idCours_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            numSalle_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            heureDebut_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            heureFin_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            idClasse_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Cours::Cours(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            heureDebut_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            heureFin_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            idClasse_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
}

Cours::Cours(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_cours"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id_cours"].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson["id_cours"].asInt64());
        }
    }
    if(pJson.isMember("num_salle"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["num_salle"].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson["num_salle"].asInt64());
        }
    }
    if(pJson.isMember("heure_debut"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["heure_debut"].isNull())
        {
            heureDebut_=std::make_shared<std::string>(pJson["heure_debut"].asString());
        }
    }
    if(pJson.isMember("heure_fin"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["heure_fin"].isNull())
        {
            heureFin_=std::make_shared<std::string>(pJson["heure_fin"].asString());
        }
    }
    if(pJson.isMember("id_classe"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["id_classe"].isNull())
        {
            idClasse_=std::make_shared<int32_t>((int32_t)pJson["id_classe"].asInt64());
        }
    }
}

void Cours::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            heureDebut_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            heureFin_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            idClasse_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
}

void Cours::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_cours"))
    {
        if(!pJson["id_cours"].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson["id_cours"].asInt64());
        }
    }
    if(pJson.isMember("num_salle"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["num_salle"].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson["num_salle"].asInt64());
        }
    }
    if(pJson.isMember("heure_debut"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["heure_debut"].isNull())
        {
            heureDebut_=std::make_shared<std::string>(pJson["heure_debut"].asString());
        }
    }
    if(pJson.isMember("heure_fin"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["heure_fin"].isNull())
        {
            heureFin_=std::make_shared<std::string>(pJson["heure_fin"].asString());
        }
    }
    if(pJson.isMember("id_classe"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["id_classe"].isNull())
        {
            idClasse_=std::make_shared<int32_t>((int32_t)pJson["id_classe"].asInt64());
        }
    }
}

const int32_t &Cours::getValueOfIdCours() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idCours_)
        return *idCours_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Cours::getIdCours() const noexcept
{
    return idCours_;
}
void Cours::setIdCours(const int32_t &pIdCours) noexcept
{
    idCours_ = std::make_shared<int32_t>(pIdCours);
    dirtyFlag_[0] = true;
}
const typename Cours::PrimaryKeyType & Cours::getPrimaryKey() const
{
    assert(idCours_);
    return *idCours_;
}

const int32_t &Cours::getValueOfNumSalle() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(numSalle_)
        return *numSalle_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Cours::getNumSalle() const noexcept
{
    return numSalle_;
}
void Cours::setNumSalle(const int32_t &pNumSalle) noexcept
{
    numSalle_ = std::make_shared<int32_t>(pNumSalle);
    dirtyFlag_[1] = true;
}

const std::string &Cours::getValueOfHeureDebut() const noexcept
{
    static const std::string defaultValue = std::string();
    if(heureDebut_)
        return *heureDebut_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Cours::getHeureDebut() const noexcept
{
    return heureDebut_;
}
void Cours::setHeureDebut(const std::string &pHeureDebut) noexcept
{
    heureDebut_ = std::make_shared<std::string>(pHeureDebut);
    dirtyFlag_[2] = true;
}
void Cours::setHeureDebut(std::string &&pHeureDebut) noexcept
{
    heureDebut_ = std::make_shared<std::string>(std::move(pHeureDebut));
    dirtyFlag_[2] = true;
}

const std::string &Cours::getValueOfHeureFin() const noexcept
{
    static const std::string defaultValue = std::string();
    if(heureFin_)
        return *heureFin_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Cours::getHeureFin() const noexcept
{
    return heureFin_;
}
void Cours::setHeureFin(const std::string &pHeureFin) noexcept
{
    heureFin_ = std::make_shared<std::string>(pHeureFin);
    dirtyFlag_[3] = true;
}
void Cours::setHeureFin(std::string &&pHeureFin) noexcept
{
    heureFin_ = std::make_shared<std::string>(std::move(pHeureFin));
    dirtyFlag_[3] = true;
}

const int32_t &Cours::getValueOfIdClasse() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idClasse_)
        return *idClasse_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Cours::getIdClasse() const noexcept
{
    return idClasse_;
}
void Cours::setIdClasse(const int32_t &pIdClasse) noexcept
{
    idClasse_ = std::make_shared<int32_t>(pIdClasse);
    dirtyFlag_[4] = true;
}
void Cours::setIdClasseToNull() noexcept
{
    idClasse_.reset();
    dirtyFlag_[4] = true;
}

void Cours::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Cours::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "num_salle",
        "heure_debut",
        "heure_fin",
        "id_classe"
    };
    return inCols;
}

void Cours::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getNumSalle())
        {
            binder << getValueOfNumSalle();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getHeureDebut())
        {
            binder << getValueOfHeureDebut();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getHeureFin())
        {
            binder << getValueOfHeureFin();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getIdClasse())
        {
            binder << getValueOfIdClasse();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Cours::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void Cours::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getNumSalle())
        {
            binder << getValueOfNumSalle();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getHeureDebut())
        {
            binder << getValueOfHeureDebut();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getHeureFin())
        {
            binder << getValueOfHeureFin();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getIdClasse())
        {
            binder << getValueOfIdClasse();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Cours::toJson() const
{
    Json::Value ret;
    if(getIdCours())
    {
        ret["id_cours"]=getValueOfIdCours();
    }
    else
    {
        ret["id_cours"]=Json::Value();
    }
    if(getNumSalle())
    {
        ret["num_salle"]=getValueOfNumSalle();
    }
    else
    {
        ret["num_salle"]=Json::Value();
    }
    if(getHeureDebut())
    {
        ret["heure_debut"]=getValueOfHeureDebut();
    }
    else
    {
        ret["heure_debut"]=Json::Value();
    }
    if(getHeureFin())
    {
        ret["heure_fin"]=getValueOfHeureFin();
    }
    else
    {
        ret["heure_fin"]=Json::Value();
    }
    if(getIdClasse())
    {
        ret["id_classe"]=getValueOfIdClasse();
    }
    else
    {
        ret["id_classe"]=Json::Value();
    }
    return ret;
}

std::string Cours::toString() const
{
    return toJson().toStyledString();
}

Json::Value Cours::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getIdCours())
            {
                ret[pMasqueradingVector[0]]=getValueOfIdCours();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getNumSalle())
            {
                ret[pMasqueradingVector[1]]=getValueOfNumSalle();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getHeureDebut())
            {
                ret[pMasqueradingVector[2]]=getValueOfHeureDebut();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getHeureFin())
            {
                ret[pMasqueradingVector[3]]=getValueOfHeureFin();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getIdClasse())
            {
                ret[pMasqueradingVector[4]]=getValueOfIdClasse();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getIdCours())
    {
        ret["id_cours"]=getValueOfIdCours();
    }
    else
    {
        ret["id_cours"]=Json::Value();
    }
    if(getNumSalle())
    {
        ret["num_salle"]=getValueOfNumSalle();
    }
    else
    {
        ret["num_salle"]=Json::Value();
    }
    if(getHeureDebut())
    {
        ret["heure_debut"]=getValueOfHeureDebut();
    }
    else
    {
        ret["heure_debut"]=Json::Value();
    }
    if(getHeureFin())
    {
        ret["heure_fin"]=getValueOfHeureFin();
    }
    else
    {
        ret["heure_fin"]=Json::Value();
    }
    if(getIdClasse())
    {
        ret["id_classe"]=getValueOfIdClasse();
    }
    else
    {
        ret["id_classe"]=Json::Value();
    }
    return ret;
}

bool Cours::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_cours"))
    {
        if(!validJsonOfField(0, "id_cours", pJson["id_cours"], err, true))
            return false;
    }
    if(pJson.isMember("num_salle"))
    {
        if(!validJsonOfField(1, "num_salle", pJson["num_salle"], err, true))
            return false;
    }
    else
    {
        err="The num_salle column cannot be null";
        return false;
    }
    if(pJson.isMember("heure_debut"))
    {
        if(!validJsonOfField(2, "heure_debut", pJson["heure_debut"], err, true))
            return false;
    }
    else
    {
        err="The heure_debut column cannot be null";
        return false;
    }
    if(pJson.isMember("heure_fin"))
    {
        if(!validJsonOfField(3, "heure_fin", pJson["heure_fin"], err, true))
            return false;
    }
    else
    {
        err="The heure_fin column cannot be null";
        return false;
    }
    if(pJson.isMember("id_classe"))
    {
        if(!validJsonOfField(4, "id_classe", pJson["id_classe"], err, true))
            return false;
    }
    return true;
}
bool Cours::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Cours::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_cours"))
    {
        if(!validJsonOfField(0, "id_cours", pJson["id_cours"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("num_salle"))
    {
        if(!validJsonOfField(1, "num_salle", pJson["num_salle"], err, false))
            return false;
    }
    if(pJson.isMember("heure_debut"))
    {
        if(!validJsonOfField(2, "heure_debut", pJson["heure_debut"], err, false))
            return false;
    }
    if(pJson.isMember("heure_fin"))
    {
        if(!validJsonOfField(3, "heure_fin", pJson["heure_fin"], err, false))
            return false;
    }
    if(pJson.isMember("id_classe"))
    {
        if(!validJsonOfField(4, "id_classe", pJson["id_classe"], err, false))
            return false;
    }
    return true;
}
bool Cours::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Cours::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
