/**
 *
 *  Historique.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Historique.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::ProjetV1;

const std::string Historique::Cols::_id_historique = "\"id_historique\"";
const std::string Historique::Cols::_id_user = "\"id_user\"";
const std::string Historique::Cols::_date_action = "\"date_action\"";
const std::string Historique::Cols::_type_action = "\"type_action\"";
const std::string Historique::primaryKeyName = "id_historique";
const bool Historique::hasPrimaryKey = true;
const std::string Historique::tableName = "\"historique\"";

const std::vector<typename Historique::MetaData> Historique::metaData_={
{"id_historique","int32_t","integer",4,1,1,1},
{"id_user","int32_t","integer",4,1,0,1},
{"date_action","::trantor::Date","timestamp without time zone",0,0,0,1},
{"type_action","std::string","character varying",50,0,0,1}
};
const std::string &Historique::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Historique::Historique(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id_historique"].isNull())
        {
            idHistorique_=std::make_shared<int32_t>(r["id_historique"].as<int32_t>());
        }
        if(!r["id_user"].isNull())
        {
            idUser_=std::make_shared<int32_t>(r["id_user"].as<int32_t>());
        }
        if(!r["date_action"].isNull())
        {
            auto timeStr = r["date_action"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateAction_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["type_action"].isNull())
        {
            typeAction_=std::make_shared<std::string>(r["type_action"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            idHistorique_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            idUser_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateAction_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            typeAction_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Historique::Historique(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idHistorique_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idUser_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateAction_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            typeAction_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

Historique::Historique(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_historique"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id_historique"].isNull())
        {
            idHistorique_=std::make_shared<int32_t>((int32_t)pJson["id_historique"].asInt64());
        }
    }
    if(pJson.isMember("id_user"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["id_user"].isNull())
        {
            idUser_=std::make_shared<int32_t>((int32_t)pJson["id_user"].asInt64());
        }
    }
    if(pJson.isMember("date_action"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["date_action"].isNull())
        {
            auto timeStr = pJson["date_action"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateAction_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("type_action"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["type_action"].isNull())
        {
            typeAction_=std::make_shared<std::string>(pJson["type_action"].asString());
        }
    }
}

void Historique::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idHistorique_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idUser_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateAction_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            typeAction_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

void Historique::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_historique"))
    {
        if(!pJson["id_historique"].isNull())
        {
            idHistorique_=std::make_shared<int32_t>((int32_t)pJson["id_historique"].asInt64());
        }
    }
    if(pJson.isMember("id_user"))
    {
        if(!pJson["id_user"].isNull())
        {
            idUser_=std::make_shared<int32_t>((int32_t)pJson["id_user"].asInt64());
        }
    }
    if(pJson.isMember("date_action"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["date_action"].isNull())
        {
            auto timeStr = pJson["date_action"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                dateAction_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("type_action"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["type_action"].isNull())
        {
            typeAction_=std::make_shared<std::string>(pJson["type_action"].asString());
        }
    }
}

const int32_t &Historique::getValueOfIdHistorique() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idHistorique_)
        return *idHistorique_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Historique::getIdHistorique() const noexcept
{
    return idHistorique_;
}
void Historique::setIdHistorique(const int32_t &pIdHistorique) noexcept
{
    idHistorique_ = std::make_shared<int32_t>(pIdHistorique);
    dirtyFlag_[0] = true;
}
const typename Historique::PrimaryKeyType & Historique::getPrimaryKey() const
{
    assert(idHistorique_);
    return *idHistorique_;
}

const int32_t &Historique::getValueOfIdUser() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idUser_)
        return *idUser_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Historique::getIdUser() const noexcept
{
    return idUser_;
}
void Historique::setIdUser(const int32_t &pIdUser) noexcept
{
    idUser_ = std::make_shared<int32_t>(pIdUser);
    dirtyFlag_[1] = true;
}

const ::trantor::Date &Historique::getValueOfDateAction() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(dateAction_)
        return *dateAction_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Historique::getDateAction() const noexcept
{
    return dateAction_;
}
void Historique::setDateAction(const ::trantor::Date &pDateAction) noexcept
{
    dateAction_ = std::make_shared<::trantor::Date>(pDateAction);
    dirtyFlag_[2] = true;
}

const std::string &Historique::getValueOfTypeAction() const noexcept
{
    static const std::string defaultValue = std::string();
    if(typeAction_)
        return *typeAction_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Historique::getTypeAction() const noexcept
{
    return typeAction_;
}
void Historique::setTypeAction(const std::string &pTypeAction) noexcept
{
    typeAction_ = std::make_shared<std::string>(pTypeAction);
    dirtyFlag_[3] = true;
}
void Historique::setTypeAction(std::string &&pTypeAction) noexcept
{
    typeAction_ = std::make_shared<std::string>(std::move(pTypeAction));
    dirtyFlag_[3] = true;
}

void Historique::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Historique::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "date_action",
        "type_action"
    };
    return inCols;
}

void Historique::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[2])
    {
        if(getDateAction())
        {
            binder << getValueOfDateAction();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getTypeAction())
        {
            binder << getValueOfTypeAction();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Historique::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void Historique::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[2])
    {
        if(getDateAction())
        {
            binder << getValueOfDateAction();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getTypeAction())
        {
            binder << getValueOfTypeAction();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Historique::toJson() const
{
    Json::Value ret;
    if(getIdHistorique())
    {
        ret["id_historique"]=getValueOfIdHistorique();
    }
    else
    {
        ret["id_historique"]=Json::Value();
    }
    if(getIdUser())
    {
        ret["id_user"]=getValueOfIdUser();
    }
    else
    {
        ret["id_user"]=Json::Value();
    }
    if(getDateAction())
    {
        ret["date_action"]=getDateAction()->toDbStringLocal();
    }
    else
    {
        ret["date_action"]=Json::Value();
    }
    if(getTypeAction())
    {
        ret["type_action"]=getValueOfTypeAction();
    }
    else
    {
        ret["type_action"]=Json::Value();
    }
    return ret;
}

std::string Historique::toString() const
{
    return toJson().toStyledString();
}

Json::Value Historique::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getIdHistorique())
            {
                ret[pMasqueradingVector[0]]=getValueOfIdHistorique();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getIdUser())
            {
                ret[pMasqueradingVector[1]]=getValueOfIdUser();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDateAction())
            {
                ret[pMasqueradingVector[2]]=getDateAction()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getTypeAction())
            {
                ret[pMasqueradingVector[3]]=getValueOfTypeAction();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getIdHistorique())
    {
        ret["id_historique"]=getValueOfIdHistorique();
    }
    else
    {
        ret["id_historique"]=Json::Value();
    }
    if(getIdUser())
    {
        ret["id_user"]=getValueOfIdUser();
    }
    else
    {
        ret["id_user"]=Json::Value();
    }
    if(getDateAction())
    {
        ret["date_action"]=getDateAction()->toDbStringLocal();
    }
    else
    {
        ret["date_action"]=Json::Value();
    }
    if(getTypeAction())
    {
        ret["type_action"]=getValueOfTypeAction();
    }
    else
    {
        ret["type_action"]=Json::Value();
    }
    return ret;
}

bool Historique::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_historique"))
    {
        if(!validJsonOfField(0, "id_historique", pJson["id_historique"], err, true))
            return false;
    }
    if(pJson.isMember("id_user"))
    {
        if(!validJsonOfField(1, "id_user", pJson["id_user"], err, true))
            return false;
    }
    if(pJson.isMember("date_action"))
    {
        if(!validJsonOfField(2, "date_action", pJson["date_action"], err, true))
            return false;
    }
    if(pJson.isMember("type_action"))
    {
        if(!validJsonOfField(3, "type_action", pJson["type_action"], err, true))
            return false;
    }
    else
    {
        err="The type_action column cannot be null";
        return false;
    }
    return true;
}
bool Historique::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Historique::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_historique"))
    {
        if(!validJsonOfField(0, "id_historique", pJson["id_historique"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("id_user"))
    {
        if(!validJsonOfField(1, "id_user", pJson["id_user"], err, false))
            return false;
    }
    if(pJson.isMember("date_action"))
    {
        if(!validJsonOfField(2, "date_action", pJson["date_action"], err, false))
            return false;
    }
    if(pJson.isMember("type_action"))
    {
        if(!validJsonOfField(3, "type_action", pJson["type_action"], err, false))
            return false;
    }
    return true;
}
bool Historique::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Historique::validJsonOfField(size_t index,
                                  const std::string &fieldName,
                                  const Json::Value &pJson,
                                  std::string &err,
                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            else
            {
                err="The automatic primary key cannot be update";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
