/**
 *
 *  Presence.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Presence.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::ProjetV1;

const std::string Presence::Cols::_id_presence = "\"id_presence\"";
const std::string Presence::Cols::_uuid_user = "\"uuid_user\"";
const std::string Presence::Cols::_id_cours = "\"id_cours\"";
const std::string Presence::Cols::_statut = "\"statut\"";
const std::string Presence::Cols::_heure_badgeage = "\"heure_badgeage\"";
const std::string Presence::Cols::_temps_retard_min = "\"temps_retard_min\"";
const std::string Presence::primaryKeyName = "id_presence";
const bool Presence::hasPrimaryKey = true;
const std::string Presence::tableName = "\"presence\"";

const std::vector<typename Presence::MetaData> Presence::metaData_={
{"id_presence","int32_t","integer",4,1,1,1},
{"uuid_user","std::string","uuid",0,0,0,1},
{"id_cours","int32_t","integer",4,0,0,1},
{"statut","std::string","character varying",20,0,0,1},
{"heure_badgeage","std::string","time without time zone",0,0,0,0},
{"temps_retard_min","int32_t","integer",4,0,0,1}
};
const std::string &Presence::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Presence::Presence(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id_presence"].isNull())
        {
            idPresence_=std::make_shared<int32_t>(r["id_presence"].as<int32_t>());
        }
        if(!r["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(r["uuid_user"].as<std::string>());
        }
        if(!r["id_cours"].isNull())
        {
            idCours_=std::make_shared<int32_t>(r["id_cours"].as<int32_t>());
        }
        if(!r["statut"].isNull())
        {
            statut_=std::make_shared<std::string>(r["statut"].as<std::string>());
        }
        if(!r["heure_badgeage"].isNull())
        {
            heureBadgeage_=std::make_shared<std::string>(r["heure_badgeage"].as<std::string>());
        }
        if(!r["temps_retard_min"].isNull())
        {
            tempsRetardMin_=std::make_shared<int32_t>(r["temps_retard_min"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            idPresence_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            uuidUser_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            idCours_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            statut_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            heureBadgeage_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            tempsRetardMin_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Presence::Presence(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idPresence_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            statut_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            heureBadgeage_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            tempsRetardMin_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
}

Presence::Presence(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_presence"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id_presence"].isNull())
        {
            idPresence_=std::make_shared<int32_t>((int32_t)pJson["id_presence"].asInt64());
        }
    }
    if(pJson.isMember("uuid_user"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson["uuid_user"].asString());
        }
    }
    if(pJson.isMember("id_cours"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["id_cours"].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson["id_cours"].asInt64());
        }
    }
    if(pJson.isMember("statut"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["statut"].isNull())
        {
            statut_=std::make_shared<std::string>(pJson["statut"].asString());
        }
    }
    if(pJson.isMember("heure_badgeage"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["heure_badgeage"].isNull())
        {
            heureBadgeage_=std::make_shared<std::string>(pJson["heure_badgeage"].asString());
        }
    }
    if(pJson.isMember("temps_retard_min"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["temps_retard_min"].isNull())
        {
            tempsRetardMin_=std::make_shared<int32_t>((int32_t)pJson["temps_retard_min"].asInt64());
        }
    }
}

void Presence::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idPresence_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            statut_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            heureBadgeage_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            tempsRetardMin_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
}

void Presence::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_presence"))
    {
        if(!pJson["id_presence"].isNull())
        {
            idPresence_=std::make_shared<int32_t>((int32_t)pJson["id_presence"].asInt64());
        }
    }
    if(pJson.isMember("uuid_user"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson["uuid_user"].asString());
        }
    }
    if(pJson.isMember("id_cours"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["id_cours"].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson["id_cours"].asInt64());
        }
    }
    if(pJson.isMember("statut"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["statut"].isNull())
        {
            statut_=std::make_shared<std::string>(pJson["statut"].asString());
        }
    }
    if(pJson.isMember("heure_badgeage"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["heure_badgeage"].isNull())
        {
            heureBadgeage_=std::make_shared<std::string>(pJson["heure_badgeage"].asString());
        }
    }
    if(pJson.isMember("temps_retard_min"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["temps_retard_min"].isNull())
        {
            tempsRetardMin_=std::make_shared<int32_t>((int32_t)pJson["temps_retard_min"].asInt64());
        }
    }
}

const int32_t &Presence::getValueOfIdPresence() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idPresence_)
        return *idPresence_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Presence::getIdPresence() const noexcept
{
    return idPresence_;
}
void Presence::setIdPresence(const int32_t &pIdPresence) noexcept
{
    idPresence_ = std::make_shared<int32_t>(pIdPresence);
    dirtyFlag_[0] = true;
}
const typename Presence::PrimaryKeyType & Presence::getPrimaryKey() const
{
    assert(idPresence_);
    return *idPresence_;
}

const std::string &Presence::getValueOfUuidUser() const noexcept
{
    static const std::string defaultValue = std::string();
    if(uuidUser_)
        return *uuidUser_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Presence::getUuidUser() const noexcept
{
    return uuidUser_;
}
void Presence::setUuidUser(const std::string &pUuidUser) noexcept
{
    uuidUser_ = std::make_shared<std::string>(pUuidUser);
    dirtyFlag_[1] = true;
}
void Presence::setUuidUser(std::string &&pUuidUser) noexcept
{
    uuidUser_ = std::make_shared<std::string>(std::move(pUuidUser));
    dirtyFlag_[1] = true;
}

const int32_t &Presence::getValueOfIdCours() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idCours_)
        return *idCours_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Presence::getIdCours() const noexcept
{
    return idCours_;
}
void Presence::setIdCours(const int32_t &pIdCours) noexcept
{
    idCours_ = std::make_shared<int32_t>(pIdCours);
    dirtyFlag_[2] = true;
}

const std::string &Presence::getValueOfStatut() const noexcept
{
    static const std::string defaultValue = std::string();
    if(statut_)
        return *statut_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Presence::getStatut() const noexcept
{
    return statut_;
}
void Presence::setStatut(const std::string &pStatut) noexcept
{
    statut_ = std::make_shared<std::string>(pStatut);
    dirtyFlag_[3] = true;
}
void Presence::setStatut(std::string &&pStatut) noexcept
{
    statut_ = std::make_shared<std::string>(std::move(pStatut));
    dirtyFlag_[3] = true;
}

const std::string &Presence::getValueOfHeureBadgeage() const noexcept
{
    static const std::string defaultValue = std::string();
    if(heureBadgeage_)
        return *heureBadgeage_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Presence::getHeureBadgeage() const noexcept
{
    return heureBadgeage_;
}
void Presence::setHeureBadgeage(const std::string &pHeureBadgeage) noexcept
{
    heureBadgeage_ = std::make_shared<std::string>(pHeureBadgeage);
    dirtyFlag_[4] = true;
}
void Presence::setHeureBadgeage(std::string &&pHeureBadgeage) noexcept
{
    heureBadgeage_ = std::make_shared<std::string>(std::move(pHeureBadgeage));
    dirtyFlag_[4] = true;
}
void Presence::setHeureBadgeageToNull() noexcept
{
    heureBadgeage_.reset();
    dirtyFlag_[4] = true;
}

const int32_t &Presence::getValueOfTempsRetardMin() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(tempsRetardMin_)
        return *tempsRetardMin_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Presence::getTempsRetardMin() const noexcept
{
    return tempsRetardMin_;
}
void Presence::setTempsRetardMin(const int32_t &pTempsRetardMin) noexcept
{
    tempsRetardMin_ = std::make_shared<int32_t>(pTempsRetardMin);
    dirtyFlag_[5] = true;
}

void Presence::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Presence::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "uuid_user",
        "id_cours",
        "statut",
        "heure_badgeage",
        "temps_retard_min"
    };
    return inCols;
}

void Presence::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUuidUser())
        {
            binder << getValueOfUuidUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIdCours())
        {
            binder << getValueOfIdCours();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getStatut())
        {
            binder << getValueOfStatut();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getHeureBadgeage())
        {
            binder << getValueOfHeureBadgeage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTempsRetardMin())
        {
            binder << getValueOfTempsRetardMin();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Presence::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void Presence::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUuidUser())
        {
            binder << getValueOfUuidUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIdCours())
        {
            binder << getValueOfIdCours();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getStatut())
        {
            binder << getValueOfStatut();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getHeureBadgeage())
        {
            binder << getValueOfHeureBadgeage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTempsRetardMin())
        {
            binder << getValueOfTempsRetardMin();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Presence::toJson() const
{
    Json::Value ret;
    if(getIdPresence())
    {
        ret["id_presence"]=getValueOfIdPresence();
    }
    else
    {
        ret["id_presence"]=Json::Value();
    }
    if(getUuidUser())
    {
        ret["uuid_user"]=getValueOfUuidUser();
    }
    else
    {
        ret["uuid_user"]=Json::Value();
    }
    if(getIdCours())
    {
        ret["id_cours"]=getValueOfIdCours();
    }
    else
    {
        ret["id_cours"]=Json::Value();
    }
    if(getStatut())
    {
        ret["statut"]=getValueOfStatut();
    }
    else
    {
        ret["statut"]=Json::Value();
    }
    if(getHeureBadgeage())
    {
        ret["heure_badgeage"]=getValueOfHeureBadgeage();
    }
    else
    {
        ret["heure_badgeage"]=Json::Value();
    }
    if(getTempsRetardMin())
    {
        ret["temps_retard_min"]=getValueOfTempsRetardMin();
    }
    else
    {
        ret["temps_retard_min"]=Json::Value();
    }
    return ret;
}

std::string Presence::toString() const
{
    return toJson().toStyledString();
}

Json::Value Presence::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getIdPresence())
            {
                ret[pMasqueradingVector[0]]=getValueOfIdPresence();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUuidUser())
            {
                ret[pMasqueradingVector[1]]=getValueOfUuidUser();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getIdCours())
            {
                ret[pMasqueradingVector[2]]=getValueOfIdCours();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getStatut())
            {
                ret[pMasqueradingVector[3]]=getValueOfStatut();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getHeureBadgeage())
            {
                ret[pMasqueradingVector[4]]=getValueOfHeureBadgeage();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getTempsRetardMin())
            {
                ret[pMasqueradingVector[5]]=getValueOfTempsRetardMin();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getIdPresence())
    {
        ret["id_presence"]=getValueOfIdPresence();
    }
    else
    {
        ret["id_presence"]=Json::Value();
    }
    if(getUuidUser())
    {
        ret["uuid_user"]=getValueOfUuidUser();
    }
    else
    {
        ret["uuid_user"]=Json::Value();
    }
    if(getIdCours())
    {
        ret["id_cours"]=getValueOfIdCours();
    }
    else
    {
        ret["id_cours"]=Json::Value();
    }
    if(getStatut())
    {
        ret["statut"]=getValueOfStatut();
    }
    else
    {
        ret["statut"]=Json::Value();
    }
    if(getHeureBadgeage())
    {
        ret["heure_badgeage"]=getValueOfHeureBadgeage();
    }
    else
    {
        ret["heure_badgeage"]=Json::Value();
    }
    if(getTempsRetardMin())
    {
        ret["temps_retard_min"]=getValueOfTempsRetardMin();
    }
    else
    {
        ret["temps_retard_min"]=Json::Value();
    }
    return ret;
}

bool Presence::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_presence"))
    {
        if(!validJsonOfField(0, "id_presence", pJson["id_presence"], err, true))
            return false;
    }
    if(pJson.isMember("uuid_user"))
    {
        if(!validJsonOfField(1, "uuid_user", pJson["uuid_user"], err, true))
            return false;
    }
    else
    {
        err="The uuid_user column cannot be null";
        return false;
    }
    if(pJson.isMember("id_cours"))
    {
        if(!validJsonOfField(2, "id_cours", pJson["id_cours"], err, true))
            return false;
    }
    else
    {
        err="The id_cours column cannot be null";
        return false;
    }
    if(pJson.isMember("statut"))
    {
        if(!validJsonOfField(3, "statut", pJson["statut"], err, true))
            return false;
    }
    else
    {
        err="The statut column cannot be null";
        return false;
    }
    if(pJson.isMember("heure_badgeage"))
    {
        if(!validJsonOfField(4, "heure_badgeage", pJson["heure_badgeage"], err, true))
            return false;
    }
    if(pJson.isMember("temps_retard_min"))
    {
        if(!validJsonOfField(5, "temps_retard_min", pJson["temps_retard_min"], err, true))
            return false;
    }
    return true;
}
bool Presence::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Presence::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_presence"))
    {
        if(!validJsonOfField(0, "id_presence", pJson["id_presence"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("uuid_user"))
    {
        if(!validJsonOfField(1, "uuid_user", pJson["uuid_user"], err, false))
            return false;
    }
    if(pJson.isMember("id_cours"))
    {
        if(!validJsonOfField(2, "id_cours", pJson["id_cours"], err, false))
            return false;
    }
    if(pJson.isMember("statut"))
    {
        if(!validJsonOfField(3, "statut", pJson["statut"], err, false))
            return false;
    }
    if(pJson.isMember("heure_badgeage"))
    {
        if(!validJsonOfField(4, "heure_badgeage", pJson["heure_badgeage"], err, false))
            return false;
    }
    if(pJson.isMember("temps_retard_min"))
    {
        if(!validJsonOfField(5, "temps_retard_min", pJson["temps_retard_min"], err, false))
            return false;
    }
    return true;
}
bool Presence::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Presence::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
