/**
 *
 *  PresenceCours.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PresenceCours.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::ProjetV1;

const std::string PresenceCours::Cols::_id_presence = "\"id_presence\"";
const std::string PresenceCours::Cols::_id_user = "\"id_user\"";
const std::string PresenceCours::Cols::_id_cours = "\"id_cours\"";
const std::string PresenceCours::Cols::_id_classe = "\"id_classe\"";
const std::string PresenceCours::primaryKeyName = "id_presence";
const bool PresenceCours::hasPrimaryKey = true;
const std::string PresenceCours::tableName = "\"presence_cours\"";

const std::vector<typename PresenceCours::MetaData> PresenceCours::metaData_={
{"id_presence","int32_t","integer",4,1,1,1},
{"id_user","int32_t","integer",4,1,0,1},
{"id_cours","int32_t","integer",4,1,0,1},
{"id_classe","int32_t","integer",4,0,0,0}
};
const std::string &PresenceCours::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PresenceCours::PresenceCours(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id_presence"].isNull())
        {
            idPresence_=std::make_shared<int32_t>(r["id_presence"].as<int32_t>());
        }
        if(!r["id_user"].isNull())
        {
            idUser_=std::make_shared<int32_t>(r["id_user"].as<int32_t>());
        }
        if(!r["id_cours"].isNull())
        {
            idCours_=std::make_shared<int32_t>(r["id_cours"].as<int32_t>());
        }
        if(!r["id_classe"].isNull())
        {
            idClasse_=std::make_shared<int32_t>(r["id_classe"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            idPresence_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            idUser_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            idCours_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            idClasse_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

PresenceCours::PresenceCours(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idPresence_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idUser_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            idClasse_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
}

PresenceCours::PresenceCours(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_presence"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id_presence"].isNull())
        {
            idPresence_=std::make_shared<int32_t>((int32_t)pJson["id_presence"].asInt64());
        }
    }
    if(pJson.isMember("id_user"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["id_user"].isNull())
        {
            idUser_=std::make_shared<int32_t>((int32_t)pJson["id_user"].asInt64());
        }
    }
    if(pJson.isMember("id_cours"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["id_cours"].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson["id_cours"].asInt64());
        }
    }
    if(pJson.isMember("id_classe"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["id_classe"].isNull())
        {
            idClasse_=std::make_shared<int32_t>((int32_t)pJson["id_classe"].asInt64());
        }
    }
}

void PresenceCours::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idPresence_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idUser_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            idClasse_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
}

void PresenceCours::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_presence"))
    {
        if(!pJson["id_presence"].isNull())
        {
            idPresence_=std::make_shared<int32_t>((int32_t)pJson["id_presence"].asInt64());
        }
    }
    if(pJson.isMember("id_user"))
    {
        if(!pJson["id_user"].isNull())
        {
            idUser_=std::make_shared<int32_t>((int32_t)pJson["id_user"].asInt64());
        }
    }
    if(pJson.isMember("id_cours"))
    {
        if(!pJson["id_cours"].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson["id_cours"].asInt64());
        }
    }
    if(pJson.isMember("id_classe"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["id_classe"].isNull())
        {
            idClasse_=std::make_shared<int32_t>((int32_t)pJson["id_classe"].asInt64());
        }
    }
}

const int32_t &PresenceCours::getValueOfIdPresence() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idPresence_)
        return *idPresence_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PresenceCours::getIdPresence() const noexcept
{
    return idPresence_;
}
void PresenceCours::setIdPresence(const int32_t &pIdPresence) noexcept
{
    idPresence_ = std::make_shared<int32_t>(pIdPresence);
    dirtyFlag_[0] = true;
}
const typename PresenceCours::PrimaryKeyType & PresenceCours::getPrimaryKey() const
{
    assert(idPresence_);
    return *idPresence_;
}

const int32_t &PresenceCours::getValueOfIdUser() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idUser_)
        return *idUser_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PresenceCours::getIdUser() const noexcept
{
    return idUser_;
}
void PresenceCours::setIdUser(const int32_t &pIdUser) noexcept
{
    idUser_ = std::make_shared<int32_t>(pIdUser);
    dirtyFlag_[1] = true;
}

const int32_t &PresenceCours::getValueOfIdCours() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idCours_)
        return *idCours_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PresenceCours::getIdCours() const noexcept
{
    return idCours_;
}
void PresenceCours::setIdCours(const int32_t &pIdCours) noexcept
{
    idCours_ = std::make_shared<int32_t>(pIdCours);
    dirtyFlag_[2] = true;
}

const int32_t &PresenceCours::getValueOfIdClasse() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idClasse_)
        return *idClasse_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PresenceCours::getIdClasse() const noexcept
{
    return idClasse_;
}
void PresenceCours::setIdClasse(const int32_t &pIdClasse) noexcept
{
    idClasse_ = std::make_shared<int32_t>(pIdClasse);
    dirtyFlag_[3] = true;
}
void PresenceCours::setIdClasseToNull() noexcept
{
    idClasse_.reset();
    dirtyFlag_[3] = true;
}

void PresenceCours::updateId(const uint64_t id)
{
}

const std::vector<std::string> &PresenceCours::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id_classe"
    };
    return inCols;
}

void PresenceCours::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[3])
    {
        if(getIdClasse())
        {
            binder << getValueOfIdClasse();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PresenceCours::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void PresenceCours::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[3])
    {
        if(getIdClasse())
        {
            binder << getValueOfIdClasse();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PresenceCours::toJson() const
{
    Json::Value ret;
    if(getIdPresence())
    {
        ret["id_presence"]=getValueOfIdPresence();
    }
    else
    {
        ret["id_presence"]=Json::Value();
    }
    if(getIdUser())
    {
        ret["id_user"]=getValueOfIdUser();
    }
    else
    {
        ret["id_user"]=Json::Value();
    }
    if(getIdCours())
    {
        ret["id_cours"]=getValueOfIdCours();
    }
    else
    {
        ret["id_cours"]=Json::Value();
    }
    if(getIdClasse())
    {
        ret["id_classe"]=getValueOfIdClasse();
    }
    else
    {
        ret["id_classe"]=Json::Value();
    }
    return ret;
}

std::string PresenceCours::toString() const
{
    return toJson().toStyledString();
}

Json::Value PresenceCours::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getIdPresence())
            {
                ret[pMasqueradingVector[0]]=getValueOfIdPresence();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getIdUser())
            {
                ret[pMasqueradingVector[1]]=getValueOfIdUser();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getIdCours())
            {
                ret[pMasqueradingVector[2]]=getValueOfIdCours();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getIdClasse())
            {
                ret[pMasqueradingVector[3]]=getValueOfIdClasse();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getIdPresence())
    {
        ret["id_presence"]=getValueOfIdPresence();
    }
    else
    {
        ret["id_presence"]=Json::Value();
    }
    if(getIdUser())
    {
        ret["id_user"]=getValueOfIdUser();
    }
    else
    {
        ret["id_user"]=Json::Value();
    }
    if(getIdCours())
    {
        ret["id_cours"]=getValueOfIdCours();
    }
    else
    {
        ret["id_cours"]=Json::Value();
    }
    if(getIdClasse())
    {
        ret["id_classe"]=getValueOfIdClasse();
    }
    else
    {
        ret["id_classe"]=Json::Value();
    }
    return ret;
}

bool PresenceCours::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_presence"))
    {
        if(!validJsonOfField(0, "id_presence", pJson["id_presence"], err, true))
            return false;
    }
    if(pJson.isMember("id_user"))
    {
        if(!validJsonOfField(1, "id_user", pJson["id_user"], err, true))
            return false;
    }
    if(pJson.isMember("id_cours"))
    {
        if(!validJsonOfField(2, "id_cours", pJson["id_cours"], err, true))
            return false;
    }
    if(pJson.isMember("id_classe"))
    {
        if(!validJsonOfField(3, "id_classe", pJson["id_classe"], err, true))
            return false;
    }
    return true;
}
bool PresenceCours::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                       const std::vector<std::string> &pMasqueradingVector,
                                                       std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PresenceCours::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_presence"))
    {
        if(!validJsonOfField(0, "id_presence", pJson["id_presence"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("id_user"))
    {
        if(!validJsonOfField(1, "id_user", pJson["id_user"], err, false))
            return false;
    }
    if(pJson.isMember("id_cours"))
    {
        if(!validJsonOfField(2, "id_cours", pJson["id_cours"], err, false))
            return false;
    }
    if(pJson.isMember("id_classe"))
    {
        if(!validJsonOfField(3, "id_classe", pJson["id_classe"], err, false))
            return false;
    }
    return true;
}
bool PresenceCours::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PresenceCours::validJsonOfField(size_t index,
                                     const std::string &fieldName,
                                     const Json::Value &pJson,
                                     std::string &err,
                                     bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            else
            {
                err="The automatic primary key cannot be update";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            else
            {
                err="The automatic primary key cannot be update";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
