/**
 *
 *  PresenceCours.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PresenceCours.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::ProjetV1;

const std::string PresenceCours::Cols::_id_presence = "\"id_presence\"";
const std::string PresenceCours::Cols::_uuid_user = "\"uuid_user\"";
const std::vector<std::string> PresenceCours::primaryKeyName = {"id_presence","uuid_user"};
const bool PresenceCours::hasPrimaryKey = true;
const std::string PresenceCours::tableName = "\"presence_cours\"";

const std::vector<typename PresenceCours::MetaData> PresenceCours::metaData_={
{"id_presence","int32_t","integer",4,0,1,1},
{"uuid_user","std::string","uuid",0,0,1,1}
};
const std::string &PresenceCours::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PresenceCours::PresenceCours(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id_presence"].isNull())
        {
            idPresence_=std::make_shared<int32_t>(r["id_presence"].as<int32_t>());
        }
        if(!r["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(r["uuid_user"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            idPresence_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            uuidUser_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

PresenceCours::PresenceCours(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idPresence_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

PresenceCours::PresenceCours(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_presence"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id_presence"].isNull())
        {
            idPresence_=std::make_shared<int32_t>((int32_t)pJson["id_presence"].asInt64());
        }
    }
    if(pJson.isMember("uuid_user"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson["uuid_user"].asString());
        }
    }
}

void PresenceCours::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idPresence_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

void PresenceCours::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_presence"))
    {
        if(!pJson["id_presence"].isNull())
        {
            idPresence_=std::make_shared<int32_t>((int32_t)pJson["id_presence"].asInt64());
        }
    }
    if(pJson.isMember("uuid_user"))
    {
        if(!pJson["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson["uuid_user"].asString());
        }
    }
}

const int32_t &PresenceCours::getValueOfIdPresence() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idPresence_)
        return *idPresence_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PresenceCours::getIdPresence() const noexcept
{
    return idPresence_;
}
void PresenceCours::setIdPresence(const int32_t &pIdPresence) noexcept
{
    idPresence_ = std::make_shared<int32_t>(pIdPresence);
    dirtyFlag_[0] = true;
}

const std::string &PresenceCours::getValueOfUuidUser() const noexcept
{
    static const std::string defaultValue = std::string();
    if(uuidUser_)
        return *uuidUser_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PresenceCours::getUuidUser() const noexcept
{
    return uuidUser_;
}
void PresenceCours::setUuidUser(const std::string &pUuidUser) noexcept
{
    uuidUser_ = std::make_shared<std::string>(pUuidUser);
    dirtyFlag_[1] = true;
}
void PresenceCours::setUuidUser(std::string &&pUuidUser) noexcept
{
    uuidUser_ = std::make_shared<std::string>(std::move(pUuidUser));
    dirtyFlag_[1] = true;
}

void PresenceCours::updateId(const uint64_t id)
{
}
typename PresenceCours::PrimaryKeyType PresenceCours::getPrimaryKey() const
{
    return std::make_tuple(*idPresence_,*uuidUser_);
}

const std::vector<std::string> &PresenceCours::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id_presence",
        "uuid_user"
    };
    return inCols;
}

void PresenceCours::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getIdPresence())
        {
            binder << getValueOfIdPresence();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUuidUser())
        {
            binder << getValueOfUuidUser();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PresenceCours::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void PresenceCours::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getIdPresence())
        {
            binder << getValueOfIdPresence();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUuidUser())
        {
            binder << getValueOfUuidUser();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PresenceCours::toJson() const
{
    Json::Value ret;
    if(getIdPresence())
    {
        ret["id_presence"]=getValueOfIdPresence();
    }
    else
    {
        ret["id_presence"]=Json::Value();
    }
    if(getUuidUser())
    {
        ret["uuid_user"]=getValueOfUuidUser();
    }
    else
    {
        ret["uuid_user"]=Json::Value();
    }
    return ret;
}

std::string PresenceCours::toString() const
{
    return toJson().toStyledString();
}

Json::Value PresenceCours::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getIdPresence())
            {
                ret[pMasqueradingVector[0]]=getValueOfIdPresence();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUuidUser())
            {
                ret[pMasqueradingVector[1]]=getValueOfUuidUser();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getIdPresence())
    {
        ret["id_presence"]=getValueOfIdPresence();
    }
    else
    {
        ret["id_presence"]=Json::Value();
    }
    if(getUuidUser())
    {
        ret["uuid_user"]=getValueOfUuidUser();
    }
    else
    {
        ret["uuid_user"]=Json::Value();
    }
    return ret;
}

bool PresenceCours::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_presence"))
    {
        if(!validJsonOfField(0, "id_presence", pJson["id_presence"], err, true))
            return false;
    }
    else
    {
        err="The id_presence column cannot be null";
        return false;
    }
    if(pJson.isMember("uuid_user"))
    {
        if(!validJsonOfField(1, "uuid_user", pJson["uuid_user"], err, true))
            return false;
    }
    else
    {
        err="The uuid_user column cannot be null";
        return false;
    }
    return true;
}
bool PresenceCours::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                       const std::vector<std::string> &pMasqueradingVector,
                                                       std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PresenceCours::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_presence"))
    {
        if(!validJsonOfField(0, "id_presence", pJson["id_presence"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("uuid_user"))
    {
        if(!validJsonOfField(1, "uuid_user", pJson["uuid_user"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool PresenceCours::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PresenceCours::validJsonOfField(size_t index,
                                     const std::string &fieldName,
                                     const Json::Value &pJson,
                                     std::string &err,
                                     bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
