/**
 *
 *  Presence.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace ProjetV1
{

class Presence
{
  public:
    struct Cols
    {
        static const std::string _id_presence;
        static const std::string _uuid_user;
        static const std::string _id_cours;
        static const std::string _statut;
        static const std::string _heure_badgeage;
        static const std::string _temps_retard_min;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Presence(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Presence(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Presence(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Presence() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id_presence  */
    ///Get the value of the column id_presence, returns the default value if the column is null
    const int32_t &getValueOfIdPresence() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getIdPresence() const noexcept;
    ///Set the value of the column id_presence
    void setIdPresence(const int32_t &pIdPresence) noexcept;

    /**  For column uuid_user  */
    ///Get the value of the column uuid_user, returns the default value if the column is null
    const std::string &getValueOfUuidUser() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUuidUser() const noexcept;
    ///Set the value of the column uuid_user
    void setUuidUser(const std::string &pUuidUser) noexcept;
    void setUuidUser(std::string &&pUuidUser) noexcept;

    /**  For column id_cours  */
    ///Get the value of the column id_cours, returns the default value if the column is null
    const int32_t &getValueOfIdCours() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getIdCours() const noexcept;
    ///Set the value of the column id_cours
    void setIdCours(const int32_t &pIdCours) noexcept;

    /**  For column statut  */
    ///Get the value of the column statut, returns the default value if the column is null
    const std::string &getValueOfStatut() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStatut() const noexcept;
    ///Set the value of the column statut
    void setStatut(const std::string &pStatut) noexcept;
    void setStatut(std::string &&pStatut) noexcept;

    /**  For column heure_badgeage  */
    ///Get the value of the column heure_badgeage, returns the default value if the column is null
    const std::string &getValueOfHeureBadgeage() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getHeureBadgeage() const noexcept;
    ///Set the value of the column heure_badgeage
    void setHeureBadgeage(const std::string &pHeureBadgeage) noexcept;
    void setHeureBadgeage(std::string &&pHeureBadgeage) noexcept;
    void setHeureBadgeageToNull() noexcept;

    /**  For column temps_retard_min  */
    ///Get the value of the column temps_retard_min, returns the default value if the column is null
    const int32_t &getValueOfTempsRetardMin() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getTempsRetardMin() const noexcept;
    ///Set the value of the column temps_retard_min
    void setTempsRetardMin(const int32_t &pTempsRetardMin) noexcept;


    static size_t getColumnNumber() noexcept {  return 6;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Presence>;
    friend drogon::orm::BaseBuilder<Presence, true, true>;
    friend drogon::orm::BaseBuilder<Presence, true, false>;
    friend drogon::orm::BaseBuilder<Presence, false, true>;
    friend drogon::orm::BaseBuilder<Presence, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Presence>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> idPresence_;
    std::shared_ptr<std::string> uuidUser_;
    std::shared_ptr<int32_t> idCours_;
    std::shared_ptr<std::string> statut_;
    std::shared_ptr<std::string> heureBadgeage_;
    std::shared_ptr<int32_t> tempsRetardMin_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[6]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id_presence = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id_presence = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id_presence,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "uuid_user,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "id_cours,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "statut,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "heure_badgeage,";
            ++parametersCount;
        }
        sql += "temps_retard_min,";
        ++parametersCount;
        if(!dirtyFlag_[5])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace ProjetV1
} // namespace drogon_model
