/**
 *
 *  Reservation.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Reservation.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::ProjetV1;

const std::string Reservation::Cols::_id_reservation = "\"id_reservation\"";
const std::string Reservation::Cols::_uuid_user = "\"uuid_user\"";
const std::string Reservation::Cols::_num_salle = "\"num_salle\"";
const std::string Reservation::Cols::_date_reservation = "\"date_reservation\"";
const std::string Reservation::Cols::_heure_debut = "\"heure_debut\"";
const std::string Reservation::Cols::_heure_fin = "\"heure_fin\"";
const std::string Reservation::primaryKeyName = "id_reservation";
const bool Reservation::hasPrimaryKey = true;
const std::string Reservation::tableName = "\"reservation\"";

const std::vector<typename Reservation::MetaData> Reservation::metaData_={
{"id_reservation","int32_t","integer",4,1,1,1},
{"uuid_user","std::string","uuid",0,0,0,1},
{"num_salle","int32_t","integer",4,0,0,1},
{"date_reservation","::trantor::Date","date",0,0,0,1},
{"heure_debut","std::string","time without time zone",0,0,0,1},
{"heure_fin","std::string","time without time zone",0,0,0,1}
};
const std::string &Reservation::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Reservation::Reservation(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id_reservation"].isNull())
        {
            idReservation_=std::make_shared<int32_t>(r["id_reservation"].as<int32_t>());
        }
        if(!r["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(r["uuid_user"].as<std::string>());
        }
        if(!r["num_salle"].isNull())
        {
            numSalle_=std::make_shared<int32_t>(r["num_salle"].as<int32_t>());
        }
        if(!r["date_reservation"].isNull())
        {
            auto daysStr = r["date_reservation"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dateReservation_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["heure_debut"].isNull())
        {
            heureDebut_=std::make_shared<std::string>(r["heure_debut"].as<std::string>());
        }
        if(!r["heure_fin"].isNull())
        {
            heureFin_=std::make_shared<std::string>(r["heure_fin"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            idReservation_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            uuidUser_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            numSalle_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dateReservation_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            heureDebut_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            heureFin_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Reservation::Reservation(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idReservation_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dateReservation_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            heureDebut_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            heureFin_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

Reservation::Reservation(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_reservation"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id_reservation"].isNull())
        {
            idReservation_=std::make_shared<int32_t>((int32_t)pJson["id_reservation"].asInt64());
        }
    }
    if(pJson.isMember("uuid_user"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson["uuid_user"].asString());
        }
    }
    if(pJson.isMember("num_salle"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["num_salle"].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson["num_salle"].asInt64());
        }
    }
    if(pJson.isMember("date_reservation"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["date_reservation"].isNull())
        {
            auto daysStr = pJson["date_reservation"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dateReservation_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("heure_debut"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["heure_debut"].isNull())
        {
            heureDebut_=std::make_shared<std::string>(pJson["heure_debut"].asString());
        }
    }
    if(pJson.isMember("heure_fin"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["heure_fin"].isNull())
        {
            heureFin_=std::make_shared<std::string>(pJson["heure_fin"].asString());
        }
    }
}

void Reservation::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idReservation_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dateReservation_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            heureDebut_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            heureFin_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

void Reservation::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_reservation"))
    {
        if(!pJson["id_reservation"].isNull())
        {
            idReservation_=std::make_shared<int32_t>((int32_t)pJson["id_reservation"].asInt64());
        }
    }
    if(pJson.isMember("uuid_user"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson["uuid_user"].asString());
        }
    }
    if(pJson.isMember("num_salle"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["num_salle"].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson["num_salle"].asInt64());
        }
    }
    if(pJson.isMember("date_reservation"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["date_reservation"].isNull())
        {
            auto daysStr = pJson["date_reservation"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dateReservation_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("heure_debut"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["heure_debut"].isNull())
        {
            heureDebut_=std::make_shared<std::string>(pJson["heure_debut"].asString());
        }
    }
    if(pJson.isMember("heure_fin"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["heure_fin"].isNull())
        {
            heureFin_=std::make_shared<std::string>(pJson["heure_fin"].asString());
        }
    }
}

const int32_t &Reservation::getValueOfIdReservation() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idReservation_)
        return *idReservation_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Reservation::getIdReservation() const noexcept
{
    return idReservation_;
}
void Reservation::setIdReservation(const int32_t &pIdReservation) noexcept
{
    idReservation_ = std::make_shared<int32_t>(pIdReservation);
    dirtyFlag_[0] = true;
}
const typename Reservation::PrimaryKeyType & Reservation::getPrimaryKey() const
{
    assert(idReservation_);
    return *idReservation_;
}

const std::string &Reservation::getValueOfUuidUser() const noexcept
{
    static const std::string defaultValue = std::string();
    if(uuidUser_)
        return *uuidUser_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Reservation::getUuidUser() const noexcept
{
    return uuidUser_;
}
void Reservation::setUuidUser(const std::string &pUuidUser) noexcept
{
    uuidUser_ = std::make_shared<std::string>(pUuidUser);
    dirtyFlag_[1] = true;
}
void Reservation::setUuidUser(std::string &&pUuidUser) noexcept
{
    uuidUser_ = std::make_shared<std::string>(std::move(pUuidUser));
    dirtyFlag_[1] = true;
}

const int32_t &Reservation::getValueOfNumSalle() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(numSalle_)
        return *numSalle_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Reservation::getNumSalle() const noexcept
{
    return numSalle_;
}
void Reservation::setNumSalle(const int32_t &pNumSalle) noexcept
{
    numSalle_ = std::make_shared<int32_t>(pNumSalle);
    dirtyFlag_[2] = true;
}

const ::trantor::Date &Reservation::getValueOfDateReservation() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(dateReservation_)
        return *dateReservation_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Reservation::getDateReservation() const noexcept
{
    return dateReservation_;
}
void Reservation::setDateReservation(const ::trantor::Date &pDateReservation) noexcept
{
    dateReservation_ = std::make_shared<::trantor::Date>(pDateReservation.roundDay());
    dirtyFlag_[3] = true;
}

const std::string &Reservation::getValueOfHeureDebut() const noexcept
{
    static const std::string defaultValue = std::string();
    if(heureDebut_)
        return *heureDebut_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Reservation::getHeureDebut() const noexcept
{
    return heureDebut_;
}
void Reservation::setHeureDebut(const std::string &pHeureDebut) noexcept
{
    heureDebut_ = std::make_shared<std::string>(pHeureDebut);
    dirtyFlag_[4] = true;
}
void Reservation::setHeureDebut(std::string &&pHeureDebut) noexcept
{
    heureDebut_ = std::make_shared<std::string>(std::move(pHeureDebut));
    dirtyFlag_[4] = true;
}

const std::string &Reservation::getValueOfHeureFin() const noexcept
{
    static const std::string defaultValue = std::string();
    if(heureFin_)
        return *heureFin_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Reservation::getHeureFin() const noexcept
{
    return heureFin_;
}
void Reservation::setHeureFin(const std::string &pHeureFin) noexcept
{
    heureFin_ = std::make_shared<std::string>(pHeureFin);
    dirtyFlag_[5] = true;
}
void Reservation::setHeureFin(std::string &&pHeureFin) noexcept
{
    heureFin_ = std::make_shared<std::string>(std::move(pHeureFin));
    dirtyFlag_[5] = true;
}

void Reservation::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Reservation::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "uuid_user",
        "num_salle",
        "date_reservation",
        "heure_debut",
        "heure_fin"
    };
    return inCols;
}

void Reservation::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUuidUser())
        {
            binder << getValueOfUuidUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNumSalle())
        {
            binder << getValueOfNumSalle();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDateReservation())
        {
            binder << getValueOfDateReservation();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getHeureDebut())
        {
            binder << getValueOfHeureDebut();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getHeureFin())
        {
            binder << getValueOfHeureFin();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Reservation::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void Reservation::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUuidUser())
        {
            binder << getValueOfUuidUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNumSalle())
        {
            binder << getValueOfNumSalle();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDateReservation())
        {
            binder << getValueOfDateReservation();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getHeureDebut())
        {
            binder << getValueOfHeureDebut();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getHeureFin())
        {
            binder << getValueOfHeureFin();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Reservation::toJson() const
{
    Json::Value ret;
    if(getIdReservation())
    {
        ret["id_reservation"]=getValueOfIdReservation();
    }
    else
    {
        ret["id_reservation"]=Json::Value();
    }
    if(getUuidUser())
    {
        ret["uuid_user"]=getValueOfUuidUser();
    }
    else
    {
        ret["uuid_user"]=Json::Value();
    }
    if(getNumSalle())
    {
        ret["num_salle"]=getValueOfNumSalle();
    }
    else
    {
        ret["num_salle"]=Json::Value();
    }
    if(getDateReservation())
    {
        ret["date_reservation"]=getDateReservation()->toDbStringLocal();
    }
    else
    {
        ret["date_reservation"]=Json::Value();
    }
    if(getHeureDebut())
    {
        ret["heure_debut"]=getValueOfHeureDebut();
    }
    else
    {
        ret["heure_debut"]=Json::Value();
    }
    if(getHeureFin())
    {
        ret["heure_fin"]=getValueOfHeureFin();
    }
    else
    {
        ret["heure_fin"]=Json::Value();
    }
    return ret;
}

std::string Reservation::toString() const
{
    return toJson().toStyledString();
}

Json::Value Reservation::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getIdReservation())
            {
                ret[pMasqueradingVector[0]]=getValueOfIdReservation();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUuidUser())
            {
                ret[pMasqueradingVector[1]]=getValueOfUuidUser();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getNumSalle())
            {
                ret[pMasqueradingVector[2]]=getValueOfNumSalle();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDateReservation())
            {
                ret[pMasqueradingVector[3]]=getDateReservation()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getHeureDebut())
            {
                ret[pMasqueradingVector[4]]=getValueOfHeureDebut();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getHeureFin())
            {
                ret[pMasqueradingVector[5]]=getValueOfHeureFin();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getIdReservation())
    {
        ret["id_reservation"]=getValueOfIdReservation();
    }
    else
    {
        ret["id_reservation"]=Json::Value();
    }
    if(getUuidUser())
    {
        ret["uuid_user"]=getValueOfUuidUser();
    }
    else
    {
        ret["uuid_user"]=Json::Value();
    }
    if(getNumSalle())
    {
        ret["num_salle"]=getValueOfNumSalle();
    }
    else
    {
        ret["num_salle"]=Json::Value();
    }
    if(getDateReservation())
    {
        ret["date_reservation"]=getDateReservation()->toDbStringLocal();
    }
    else
    {
        ret["date_reservation"]=Json::Value();
    }
    if(getHeureDebut())
    {
        ret["heure_debut"]=getValueOfHeureDebut();
    }
    else
    {
        ret["heure_debut"]=Json::Value();
    }
    if(getHeureFin())
    {
        ret["heure_fin"]=getValueOfHeureFin();
    }
    else
    {
        ret["heure_fin"]=Json::Value();
    }
    return ret;
}

bool Reservation::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_reservation"))
    {
        if(!validJsonOfField(0, "id_reservation", pJson["id_reservation"], err, true))
            return false;
    }
    if(pJson.isMember("uuid_user"))
    {
        if(!validJsonOfField(1, "uuid_user", pJson["uuid_user"], err, true))
            return false;
    }
    else
    {
        err="The uuid_user column cannot be null";
        return false;
    }
    if(pJson.isMember("num_salle"))
    {
        if(!validJsonOfField(2, "num_salle", pJson["num_salle"], err, true))
            return false;
    }
    else
    {
        err="The num_salle column cannot be null";
        return false;
    }
    if(pJson.isMember("date_reservation"))
    {
        if(!validJsonOfField(3, "date_reservation", pJson["date_reservation"], err, true))
            return false;
    }
    else
    {
        err="The date_reservation column cannot be null";
        return false;
    }
    if(pJson.isMember("heure_debut"))
    {
        if(!validJsonOfField(4, "heure_debut", pJson["heure_debut"], err, true))
            return false;
    }
    else
    {
        err="The heure_debut column cannot be null";
        return false;
    }
    if(pJson.isMember("heure_fin"))
    {
        if(!validJsonOfField(5, "heure_fin", pJson["heure_fin"], err, true))
            return false;
    }
    else
    {
        err="The heure_fin column cannot be null";
        return false;
    }
    return true;
}
bool Reservation::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Reservation::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_reservation"))
    {
        if(!validJsonOfField(0, "id_reservation", pJson["id_reservation"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("uuid_user"))
    {
        if(!validJsonOfField(1, "uuid_user", pJson["uuid_user"], err, false))
            return false;
    }
    if(pJson.isMember("num_salle"))
    {
        if(!validJsonOfField(2, "num_salle", pJson["num_salle"], err, false))
            return false;
    }
    if(pJson.isMember("date_reservation"))
    {
        if(!validJsonOfField(3, "date_reservation", pJson["date_reservation"], err, false))
            return false;
    }
    if(pJson.isMember("heure_debut"))
    {
        if(!validJsonOfField(4, "heure_debut", pJson["heure_debut"], err, false))
            return false;
    }
    if(pJson.isMember("heure_fin"))
    {
        if(!validJsonOfField(5, "heure_fin", pJson["heure_fin"], err, false))
            return false;
    }
    return true;
}
bool Reservation::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Reservation::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
