/**
 *
 *  Retardabsence.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace acces_campus_bdd
{

class Retardabsence
{
  public:
    struct Cols
    {
        static const std::string _id_retardabsence;
        static const std::string _id_user;
        static const std::string _id_cours;
        static const std::string _temps_retard_min;
        static const std::string _absence;
        static const std::string _timestamp_heure_cours;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Retardabsence(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Retardabsence(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Retardabsence(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Retardabsence() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id_retardabsence  */
    ///Get the value of the column id_retardabsence, returns the default value if the column is null
    const int32_t &getValueOfIdRetardabsence() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getIdRetardabsence() const noexcept;
    ///Set the value of the column id_retardabsence
    void setIdRetardabsence(const int32_t &pIdRetardabsence) noexcept;

    /**  For column id_user  */
    ///Get the value of the column id_user, returns the default value if the column is null
    const int32_t &getValueOfIdUser() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getIdUser() const noexcept;
    ///Set the value of the column id_user
    void setIdUser(const int32_t &pIdUser) noexcept;

    /**  For column id_cours  */
    ///Get the value of the column id_cours, returns the default value if the column is null
    const int32_t &getValueOfIdCours() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getIdCours() const noexcept;
    ///Set the value of the column id_cours
    void setIdCours(const int32_t &pIdCours) noexcept;

    /**  For column temps_retard_min  */
    ///Get the value of the column temps_retard_min, returns the default value if the column is null
    const int32_t &getValueOfTempsRetardMin() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getTempsRetardMin() const noexcept;
    ///Set the value of the column temps_retard_min
    void setTempsRetardMin(const int32_t &pTempsRetardMin) noexcept;
    void setTempsRetardMinToNull() noexcept;

    /**  For column absence  */
    ///Get the value of the column absence, returns the default value if the column is null
    const bool &getValueOfAbsence() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getAbsence() const noexcept;
    ///Set the value of the column absence
    void setAbsence(const bool &pAbsence) noexcept;

    /**  For column timestamp_heure_cours  */
    ///Get the value of the column timestamp_heure_cours, returns the default value if the column is null
    const ::trantor::Date &getValueOfTimestampHeureCours() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getTimestampHeureCours() const noexcept;
    ///Set the value of the column timestamp_heure_cours
    void setTimestampHeureCours(const ::trantor::Date &pTimestampHeureCours) noexcept;
    void setTimestampHeureCoursToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 6;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Retardabsence>;
    friend drogon::orm::BaseBuilder<Retardabsence, true, true>;
    friend drogon::orm::BaseBuilder<Retardabsence, true, false>;
    friend drogon::orm::BaseBuilder<Retardabsence, false, true>;
    friend drogon::orm::BaseBuilder<Retardabsence, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Retardabsence>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> idRetardabsence_;
    std::shared_ptr<int32_t> idUser_;
    std::shared_ptr<int32_t> idCours_;
    std::shared_ptr<int32_t> tempsRetardMin_;
    std::shared_ptr<bool> absence_;
    std::shared_ptr<::trantor::Date> timestampHeureCours_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[6]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id_retardabsence = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id_retardabsence = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id_retardabsence,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "id_user,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "id_cours,";
            ++parametersCount;
        }
        sql += "temps_retard_min,";
        ++parametersCount;
        if(!dirtyFlag_[3])
        {
            needSelection=true;
        }
        if(dirtyFlag_[4])
        {
            sql += "absence,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "timestamp_heure_cours,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace acces_campus_bdd
} // namespace drogon_model
