/**
 *
 *  Retardabsence.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Retardabsence.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::ProjetV1;

const std::string Retardabsence::Cols::_id_retardabsence = "\"id_retardabsence\"";
const std::string Retardabsence::Cols::_uuid_user = "\"uuid_user\"";
const std::string Retardabsence::Cols::_id_cours = "\"id_cours\"";
const std::string Retardabsence::Cols::_temps_retard_min = "\"temps_retard_min\"";
const std::string Retardabsence::Cols::_absence = "\"absence\"";
const std::string Retardabsence::primaryKeyName = "id_retardabsence";
const bool Retardabsence::hasPrimaryKey = true;
const std::string Retardabsence::tableName = "\"retardabsence\"";

const std::vector<typename Retardabsence::MetaData> Retardabsence::metaData_={
{"id_retardabsence","int32_t","integer",4,1,1,1},
{"uuid_user","std::string","uuid",0,0,0,1},
{"id_cours","int32_t","integer",4,0,0,1},
{"temps_retard_min","int32_t","integer",4,0,0,0},
{"absence","bool","boolean",1,0,0,1}
};
const std::string &Retardabsence::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Retardabsence::Retardabsence(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id_retardabsence"].isNull())
        {
            idRetardabsence_=std::make_shared<int32_t>(r["id_retardabsence"].as<int32_t>());
        }
        if(!r["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(r["uuid_user"].as<std::string>());
        }
        if(!r["id_cours"].isNull())
        {
            idCours_=std::make_shared<int32_t>(r["id_cours"].as<int32_t>());
        }
        if(!r["temps_retard_min"].isNull())
        {
            tempsRetardMin_=std::make_shared<int32_t>(r["temps_retard_min"].as<int32_t>());
        }
        if(!r["absence"].isNull())
        {
            absence_=std::make_shared<bool>(r["absence"].as<bool>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            idRetardabsence_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            uuidUser_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            idCours_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            tempsRetardMin_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            absence_=std::make_shared<bool>(r[index].as<bool>());
        }
    }

}

Retardabsence::Retardabsence(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idRetardabsence_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            tempsRetardMin_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            absence_=std::make_shared<bool>(pJson[pMasqueradingVector[4]].asBool());
        }
    }
}

Retardabsence::Retardabsence(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_retardabsence"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id_retardabsence"].isNull())
        {
            idRetardabsence_=std::make_shared<int32_t>((int32_t)pJson["id_retardabsence"].asInt64());
        }
    }
    if(pJson.isMember("uuid_user"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson["uuid_user"].asString());
        }
    }
    if(pJson.isMember("id_cours"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["id_cours"].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson["id_cours"].asInt64());
        }
    }
    if(pJson.isMember("temps_retard_min"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["temps_retard_min"].isNull())
        {
            tempsRetardMin_=std::make_shared<int32_t>((int32_t)pJson["temps_retard_min"].asInt64());
        }
    }
    if(pJson.isMember("absence"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["absence"].isNull())
        {
            absence_=std::make_shared<bool>(pJson["absence"].asBool());
        }
    }
}

void Retardabsence::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            idRetardabsence_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            tempsRetardMin_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            absence_=std::make_shared<bool>(pJson[pMasqueradingVector[4]].asBool());
        }
    }
}

void Retardabsence::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id_retardabsence"))
    {
        if(!pJson["id_retardabsence"].isNull())
        {
            idRetardabsence_=std::make_shared<int32_t>((int32_t)pJson["id_retardabsence"].asInt64());
        }
    }
    if(pJson.isMember("uuid_user"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson["uuid_user"].asString());
        }
    }
    if(pJson.isMember("id_cours"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["id_cours"].isNull())
        {
            idCours_=std::make_shared<int32_t>((int32_t)pJson["id_cours"].asInt64());
        }
    }
    if(pJson.isMember("temps_retard_min"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["temps_retard_min"].isNull())
        {
            tempsRetardMin_=std::make_shared<int32_t>((int32_t)pJson["temps_retard_min"].asInt64());
        }
    }
    if(pJson.isMember("absence"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["absence"].isNull())
        {
            absence_=std::make_shared<bool>(pJson["absence"].asBool());
        }
    }
}

const int32_t &Retardabsence::getValueOfIdRetardabsence() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idRetardabsence_)
        return *idRetardabsence_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Retardabsence::getIdRetardabsence() const noexcept
{
    return idRetardabsence_;
}
void Retardabsence::setIdRetardabsence(const int32_t &pIdRetardabsence) noexcept
{
    idRetardabsence_ = std::make_shared<int32_t>(pIdRetardabsence);
    dirtyFlag_[0] = true;
}
const typename Retardabsence::PrimaryKeyType & Retardabsence::getPrimaryKey() const
{
    assert(idRetardabsence_);
    return *idRetardabsence_;
}

const std::string &Retardabsence::getValueOfUuidUser() const noexcept
{
    static const std::string defaultValue = std::string();
    if(uuidUser_)
        return *uuidUser_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Retardabsence::getUuidUser() const noexcept
{
    return uuidUser_;
}
void Retardabsence::setUuidUser(const std::string &pUuidUser) noexcept
{
    uuidUser_ = std::make_shared<std::string>(pUuidUser);
    dirtyFlag_[1] = true;
}
void Retardabsence::setUuidUser(std::string &&pUuidUser) noexcept
{
    uuidUser_ = std::make_shared<std::string>(std::move(pUuidUser));
    dirtyFlag_[1] = true;
}

const int32_t &Retardabsence::getValueOfIdCours() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(idCours_)
        return *idCours_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Retardabsence::getIdCours() const noexcept
{
    return idCours_;
}
void Retardabsence::setIdCours(const int32_t &pIdCours) noexcept
{
    idCours_ = std::make_shared<int32_t>(pIdCours);
    dirtyFlag_[2] = true;
}

const int32_t &Retardabsence::getValueOfTempsRetardMin() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(tempsRetardMin_)
        return *tempsRetardMin_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Retardabsence::getTempsRetardMin() const noexcept
{
    return tempsRetardMin_;
}
void Retardabsence::setTempsRetardMin(const int32_t &pTempsRetardMin) noexcept
{
    tempsRetardMin_ = std::make_shared<int32_t>(pTempsRetardMin);
    dirtyFlag_[3] = true;
}
void Retardabsence::setTempsRetardMinToNull() noexcept
{
    tempsRetardMin_.reset();
    dirtyFlag_[3] = true;
}

const bool &Retardabsence::getValueOfAbsence() const noexcept
{
    static const bool defaultValue = bool();
    if(absence_)
        return *absence_;
    return defaultValue;
}
const std::shared_ptr<bool> &Retardabsence::getAbsence() const noexcept
{
    return absence_;
}
void Retardabsence::setAbsence(const bool &pAbsence) noexcept
{
    absence_ = std::make_shared<bool>(pAbsence);
    dirtyFlag_[4] = true;
}

void Retardabsence::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Retardabsence::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "uuid_user",
        "id_cours",
        "temps_retard_min",
        "absence"
    };
    return inCols;
}

void Retardabsence::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUuidUser())
        {
            binder << getValueOfUuidUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIdCours())
        {
            binder << getValueOfIdCours();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getTempsRetardMin())
        {
            binder << getValueOfTempsRetardMin();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getAbsence())
        {
            binder << getValueOfAbsence();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Retardabsence::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void Retardabsence::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUuidUser())
        {
            binder << getValueOfUuidUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIdCours())
        {
            binder << getValueOfIdCours();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getTempsRetardMin())
        {
            binder << getValueOfTempsRetardMin();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getAbsence())
        {
            binder << getValueOfAbsence();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Retardabsence::toJson() const
{
    Json::Value ret;
    if(getIdRetardabsence())
    {
        ret["id_retardabsence"]=getValueOfIdRetardabsence();
    }
    else
    {
        ret["id_retardabsence"]=Json::Value();
    }
    if(getUuidUser())
    {
        ret["uuid_user"]=getValueOfUuidUser();
    }
    else
    {
        ret["uuid_user"]=Json::Value();
    }
    if(getIdCours())
    {
        ret["id_cours"]=getValueOfIdCours();
    }
    else
    {
        ret["id_cours"]=Json::Value();
    }
    if(getTempsRetardMin())
    {
        ret["temps_retard_min"]=getValueOfTempsRetardMin();
    }
    else
    {
        ret["temps_retard_min"]=Json::Value();
    }
    if(getAbsence())
    {
        ret["absence"]=getValueOfAbsence();
    }
    else
    {
        ret["absence"]=Json::Value();
    }
    return ret;
}

std::string Retardabsence::toString() const
{
    return toJson().toStyledString();
}

Json::Value Retardabsence::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getIdRetardabsence())
            {
                ret[pMasqueradingVector[0]]=getValueOfIdRetardabsence();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUuidUser())
            {
                ret[pMasqueradingVector[1]]=getValueOfUuidUser();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getIdCours())
            {
                ret[pMasqueradingVector[2]]=getValueOfIdCours();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getTempsRetardMin())
            {
                ret[pMasqueradingVector[3]]=getValueOfTempsRetardMin();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getAbsence())
            {
                ret[pMasqueradingVector[4]]=getValueOfAbsence();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getIdRetardabsence())
    {
        ret["id_retardabsence"]=getValueOfIdRetardabsence();
    }
    else
    {
        ret["id_retardabsence"]=Json::Value();
    }
    if(getUuidUser())
    {
        ret["uuid_user"]=getValueOfUuidUser();
    }
    else
    {
        ret["uuid_user"]=Json::Value();
    }
    if(getIdCours())
    {
        ret["id_cours"]=getValueOfIdCours();
    }
    else
    {
        ret["id_cours"]=Json::Value();
    }
    if(getTempsRetardMin())
    {
        ret["temps_retard_min"]=getValueOfTempsRetardMin();
    }
    else
    {
        ret["temps_retard_min"]=Json::Value();
    }
    if(getAbsence())
    {
        ret["absence"]=getValueOfAbsence();
    }
    else
    {
        ret["absence"]=Json::Value();
    }
    return ret;
}

bool Retardabsence::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_retardabsence"))
    {
        if(!validJsonOfField(0, "id_retardabsence", pJson["id_retardabsence"], err, true))
            return false;
    }
    if(pJson.isMember("uuid_user"))
    {
        if(!validJsonOfField(1, "uuid_user", pJson["uuid_user"], err, true))
            return false;
    }
    else
    {
        err="The uuid_user column cannot be null";
        return false;
    }
    if(pJson.isMember("id_cours"))
    {
        if(!validJsonOfField(2, "id_cours", pJson["id_cours"], err, true))
            return false;
    }
    else
    {
        err="The id_cours column cannot be null";
        return false;
    }
    if(pJson.isMember("temps_retard_min"))
    {
        if(!validJsonOfField(3, "temps_retard_min", pJson["temps_retard_min"], err, true))
            return false;
    }
    if(pJson.isMember("absence"))
    {
        if(!validJsonOfField(4, "absence", pJson["absence"], err, true))
            return false;
    }
    else
    {
        err="The absence column cannot be null";
        return false;
    }
    return true;
}
bool Retardabsence::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                       const std::vector<std::string> &pMasqueradingVector,
                                                       std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Retardabsence::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id_retardabsence"))
    {
        if(!validJsonOfField(0, "id_retardabsence", pJson["id_retardabsence"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("uuid_user"))
    {
        if(!validJsonOfField(1, "uuid_user", pJson["uuid_user"], err, false))
            return false;
    }
    if(pJson.isMember("id_cours"))
    {
        if(!validJsonOfField(2, "id_cours", pJson["id_cours"], err, false))
            return false;
    }
    if(pJson.isMember("temps_retard_min"))
    {
        if(!validJsonOfField(3, "temps_retard_min", pJson["temps_retard_min"], err, false))
            return false;
    }
    if(pJson.isMember("absence"))
    {
        if(!validJsonOfField(4, "absence", pJson["absence"], err, false))
            return false;
    }
    return true;
}
bool Retardabsence::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Retardabsence::validJsonOfField(size_t index,
                                     const std::string &fieldName,
                                     const Json::Value &pJson,
                                     std::string &err,
                                     bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
