/**
 *
 *  Salle.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Salle.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::ProjetV1;

const std::string Salle::Cols::_num_salle = "\"num_salle\"";
const std::string Salle::Cols::_place_maximum = "\"place_maximum\"";
const std::string Salle::primaryKeyName = "num_salle";
const bool Salle::hasPrimaryKey = true;
const std::string Salle::tableName = "\"salle\"";

const std::vector<typename Salle::MetaData> Salle::metaData_={
{"num_salle","int32_t","integer",4,0,1,1},
{"place_maximum","int32_t","integer",4,0,0,1}
};
const std::string &Salle::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Salle::Salle(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["num_salle"].isNull())
        {
            numSalle_=std::make_shared<int32_t>(r["num_salle"].as<int32_t>());
        }
        if(!r["place_maximum"].isNull())
        {
            placeMaximum_=std::make_shared<int32_t>(r["place_maximum"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            numSalle_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            placeMaximum_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Salle::Salle(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            placeMaximum_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

Salle::Salle(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("num_salle"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["num_salle"].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson["num_salle"].asInt64());
        }
    }
    if(pJson.isMember("place_maximum"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["place_maximum"].isNull())
        {
            placeMaximum_=std::make_shared<int32_t>((int32_t)pJson["place_maximum"].asInt64());
        }
    }
}

void Salle::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            placeMaximum_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

void Salle::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("num_salle"))
    {
        if(!pJson["num_salle"].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson["num_salle"].asInt64());
        }
    }
    if(pJson.isMember("place_maximum"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["place_maximum"].isNull())
        {
            placeMaximum_=std::make_shared<int32_t>((int32_t)pJson["place_maximum"].asInt64());
        }
    }
}

const int32_t &Salle::getValueOfNumSalle() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(numSalle_)
        return *numSalle_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Salle::getNumSalle() const noexcept
{
    return numSalle_;
}
void Salle::setNumSalle(const int32_t &pNumSalle) noexcept
{
    numSalle_ = std::make_shared<int32_t>(pNumSalle);
    dirtyFlag_[0] = true;
}
const typename Salle::PrimaryKeyType & Salle::getPrimaryKey() const
{
    assert(numSalle_);
    return *numSalle_;
}

const int32_t &Salle::getValueOfPlaceMaximum() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(placeMaximum_)
        return *placeMaximum_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Salle::getPlaceMaximum() const noexcept
{
    return placeMaximum_;
}
void Salle::setPlaceMaximum(const int32_t &pPlaceMaximum) noexcept
{
    placeMaximum_ = std::make_shared<int32_t>(pPlaceMaximum);
    dirtyFlag_[1] = true;
}

void Salle::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Salle::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "num_salle",
        "place_maximum"
    };
    return inCols;
}

void Salle::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getNumSalle())
        {
            binder << getValueOfNumSalle();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getPlaceMaximum())
        {
            binder << getValueOfPlaceMaximum();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Salle::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void Salle::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getNumSalle())
        {
            binder << getValueOfNumSalle();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getPlaceMaximum())
        {
            binder << getValueOfPlaceMaximum();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Salle::toJson() const
{
    Json::Value ret;
    if(getNumSalle())
    {
        ret["num_salle"]=getValueOfNumSalle();
    }
    else
    {
        ret["num_salle"]=Json::Value();
    }
    if(getPlaceMaximum())
    {
        ret["place_maximum"]=getValueOfPlaceMaximum();
    }
    else
    {
        ret["place_maximum"]=Json::Value();
    }
    return ret;
}

std::string Salle::toString() const
{
    return toJson().toStyledString();
}

Json::Value Salle::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getNumSalle())
            {
                ret[pMasqueradingVector[0]]=getValueOfNumSalle();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getPlaceMaximum())
            {
                ret[pMasqueradingVector[1]]=getValueOfPlaceMaximum();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getNumSalle())
    {
        ret["num_salle"]=getValueOfNumSalle();
    }
    else
    {
        ret["num_salle"]=Json::Value();
    }
    if(getPlaceMaximum())
    {
        ret["place_maximum"]=getValueOfPlaceMaximum();
    }
    else
    {
        ret["place_maximum"]=Json::Value();
    }
    return ret;
}

bool Salle::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("num_salle"))
    {
        if(!validJsonOfField(0, "num_salle", pJson["num_salle"], err, true))
            return false;
    }
    else
    {
        err="The num_salle column cannot be null";
        return false;
    }
    if(pJson.isMember("place_maximum"))
    {
        if(!validJsonOfField(1, "place_maximum", pJson["place_maximum"], err, true))
            return false;
    }
    else
    {
        err="The place_maximum column cannot be null";
        return false;
    }
    return true;
}
bool Salle::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Salle::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("num_salle"))
    {
        if(!validJsonOfField(0, "num_salle", pJson["num_salle"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("place_maximum"))
    {
        if(!validJsonOfField(1, "place_maximum", pJson["place_maximum"], err, false))
            return false;
    }
    return true;
}
bool Salle::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Salle::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
