/**
 *
 *  Salle.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Salle.h"
#include <drogon/utils/Utilities.h>
#include <string>
#include <codecvt>
#include <locale>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::ProjetV1;

const std::string Salle::Cols::_num_salle = "\"num_salle\"";
const std::string Salle::Cols::_place_maximum = "\"place_maximum\"";
const std::string Salle::Cols::_mac_bae = "\"mac_bae\"";
const std::string Salle::Cols::_mac_pea = "\"mac_pea\"";
const std::string Salle::primaryKeyName = "num_salle";
const bool Salle::hasPrimaryKey = true;
const std::string Salle::tableName = "\"salle\"";

const std::vector<typename Salle::MetaData> Salle::metaData_={
{"num_salle","int32_t","integer",4,0,1,1},
{"place_maximum","int32_t","integer",4,0,0,1},
{"mac_bae","std::string","character varying",17,0,0,0},
{"mac_pea","std::string","character varying",17,0,0,0}
};
const std::string &Salle::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Salle::Salle(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["num_salle"].isNull())
        {
            numSalle_=std::make_shared<int32_t>(r["num_salle"].as<int32_t>());
        }
        if(!r["place_maximum"].isNull())
        {
            placeMaximum_=std::make_shared<int32_t>(r["place_maximum"].as<int32_t>());
        }
        if(!r["mac_bae"].isNull())
        {
            macBae_=std::make_shared<std::string>(r["mac_bae"].as<std::string>());
        }
        if(!r["mac_pea"].isNull())
        {
            macPea_=std::make_shared<std::string>(r["mac_pea"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            numSalle_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            placeMaximum_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            macBae_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            macPea_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Salle::Salle(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            placeMaximum_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            macBae_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            macPea_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

Salle::Salle(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("num_salle"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["num_salle"].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson["num_salle"].asInt64());
        }
    }
    if(pJson.isMember("place_maximum"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["place_maximum"].isNull())
        {
            placeMaximum_=std::make_shared<int32_t>((int32_t)pJson["place_maximum"].asInt64());
        }
    }
    if(pJson.isMember("mac_bae"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["mac_bae"].isNull())
        {
            macBae_=std::make_shared<std::string>(pJson["mac_bae"].asString());
        }
    }
    if(pJson.isMember("mac_pea"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["mac_pea"].isNull())
        {
            macPea_=std::make_shared<std::string>(pJson["mac_pea"].asString());
        }
    }
}

void Salle::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            placeMaximum_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            macBae_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            macPea_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

void Salle::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("num_salle"))
    {
        if(!pJson["num_salle"].isNull())
        {
            numSalle_=std::make_shared<int32_t>((int32_t)pJson["num_salle"].asInt64());
        }
    }
    if(pJson.isMember("place_maximum"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["place_maximum"].isNull())
        {
            placeMaximum_=std::make_shared<int32_t>((int32_t)pJson["place_maximum"].asInt64());
        }
    }
    if(pJson.isMember("mac_bae"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["mac_bae"].isNull())
        {
            macBae_=std::make_shared<std::string>(pJson["mac_bae"].asString());
        }
    }
    if(pJson.isMember("mac_pea"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["mac_pea"].isNull())
        {
            macPea_=std::make_shared<std::string>(pJson["mac_pea"].asString());
        }
    }
}

const int32_t &Salle::getValueOfNumSalle() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(numSalle_)
        return *numSalle_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Salle::getNumSalle() const noexcept
{
    return numSalle_;
}
void Salle::setNumSalle(const int32_t &pNumSalle) noexcept
{
    numSalle_ = std::make_shared<int32_t>(pNumSalle);
    dirtyFlag_[0] = true;
}
const typename Salle::PrimaryKeyType & Salle::getPrimaryKey() const
{
    assert(numSalle_);
    return *numSalle_;
}

const int32_t &Salle::getValueOfPlaceMaximum() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(placeMaximum_)
        return *placeMaximum_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Salle::getPlaceMaximum() const noexcept
{
    return placeMaximum_;
}
void Salle::setPlaceMaximum(const int32_t &pPlaceMaximum) noexcept
{
    placeMaximum_ = std::make_shared<int32_t>(pPlaceMaximum);
    dirtyFlag_[1] = true;
}

const std::string &Salle::getValueOfMacBae() const noexcept
{
    static const std::string defaultValue = std::string();
    if(macBae_)
        return *macBae_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Salle::getMacBae() const noexcept
{
    return macBae_;
}
void Salle::setMacBae(const std::string &pMacBae) noexcept
{
    macBae_ = std::make_shared<std::string>(pMacBae);
    dirtyFlag_[2] = true;
}
void Salle::setMacBae(std::string &&pMacBae) noexcept
{
    macBae_ = std::make_shared<std::string>(std::move(pMacBae));
    dirtyFlag_[2] = true;
}
void Salle::setMacBaeToNull() noexcept
{
    macBae_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Salle::getValueOfMacPea() const noexcept
{
    static const std::string defaultValue = std::string();
    if(macPea_)
        return *macPea_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Salle::getMacPea() const noexcept
{
    return macPea_;
}
void Salle::setMacPea(const std::string &pMacPea) noexcept
{
    macPea_ = std::make_shared<std::string>(pMacPea);
    dirtyFlag_[3] = true;
}
void Salle::setMacPea(std::string &&pMacPea) noexcept
{
    macPea_ = std::make_shared<std::string>(std::move(pMacPea));
    dirtyFlag_[3] = true;
}
void Salle::setMacPeaToNull() noexcept
{
    macPea_.reset();
    dirtyFlag_[3] = true;
}

void Salle::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Salle::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "num_salle",
        "place_maximum",
        "mac_bae",
        "mac_pea"
    };
    return inCols;
}

void Salle::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getNumSalle())
        {
            binder << getValueOfNumSalle();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getPlaceMaximum())
        {
            binder << getValueOfPlaceMaximum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMacBae())
        {
            binder << getValueOfMacBae();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getMacPea())
        {
            binder << getValueOfMacPea();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Salle::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void Salle::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getNumSalle())
        {
            binder << getValueOfNumSalle();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getPlaceMaximum())
        {
            binder << getValueOfPlaceMaximum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMacBae())
        {
            binder << getValueOfMacBae();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getMacPea())
        {
            binder << getValueOfMacPea();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Salle::toJson() const
{
    Json::Value ret;
    if(getNumSalle())
    {
        ret["num_salle"]=getValueOfNumSalle();
    }
    else
    {
        ret["num_salle"]=Json::Value();
    }
    if(getPlaceMaximum())
    {
        ret["place_maximum"]=getValueOfPlaceMaximum();
    }
    else
    {
        ret["place_maximum"]=Json::Value();
    }
    if(getMacBae())
    {
        ret["mac_bae"]=getValueOfMacBae();
    }
    else
    {
        ret["mac_bae"]=Json::Value();
    }
    if(getMacPea())
    {
        ret["mac_pea"]=getValueOfMacPea();
    }
    else
    {
        ret["mac_pea"]=Json::Value();
    }
    return ret;
}

std::string Salle::toString() const
{
    return toJson().toStyledString();
}

Json::Value Salle::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getNumSalle())
            {
                ret[pMasqueradingVector[0]]=getValueOfNumSalle();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getPlaceMaximum())
            {
                ret[pMasqueradingVector[1]]=getValueOfPlaceMaximum();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getMacBae())
            {
                ret[pMasqueradingVector[2]]=getValueOfMacBae();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getMacPea())
            {
                ret[pMasqueradingVector[3]]=getValueOfMacPea();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getNumSalle())
    {
        ret["num_salle"]=getValueOfNumSalle();
    }
    else
    {
        ret["num_salle"]=Json::Value();
    }
    if(getPlaceMaximum())
    {
        ret["place_maximum"]=getValueOfPlaceMaximum();
    }
    else
    {
        ret["place_maximum"]=Json::Value();
    }
    if(getMacBae())
    {
        ret["mac_bae"]=getValueOfMacBae();
    }
    else
    {
        ret["mac_bae"]=Json::Value();
    }
    if(getMacPea())
    {
        ret["mac_pea"]=getValueOfMacPea();
    }
    else
    {
        ret["mac_pea"]=Json::Value();
    }
    return ret;
}

bool Salle::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("num_salle"))
    {
        if(!validJsonOfField(0, "num_salle", pJson["num_salle"], err, true))
            return false;
    }
    else
    {
        err="The num_salle column cannot be null";
        return false;
    }
    if(pJson.isMember("place_maximum"))
    {
        if(!validJsonOfField(1, "place_maximum", pJson["place_maximum"], err, true))
            return false;
    }
    else
    {
        err="The place_maximum column cannot be null";
        return false;
    }
    if(pJson.isMember("mac_bae"))
    {
        if(!validJsonOfField(2, "mac_bae", pJson["mac_bae"], err, true))
            return false;
    }
    if(pJson.isMember("mac_pea"))
    {
        if(!validJsonOfField(3, "mac_pea", pJson["mac_pea"], err, true))
            return false;
    }
    return true;
}
bool Salle::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Salle::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("num_salle"))
    {
        if(!validJsonOfField(0, "num_salle", pJson["num_salle"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("place_maximum"))
    {
        if(!validJsonOfField(1, "place_maximum", pJson["place_maximum"], err, false))
            return false;
    }
    if(pJson.isMember("mac_bae"))
    {
        if(!validJsonOfField(2, "mac_bae", pJson["mac_bae"], err, false))
            return false;
    }
    if(pJson.isMember("mac_pea"))
    {
        if(!validJsonOfField(3, "mac_pea", pJson["mac_pea"], err, false))
            return false;
    }
    return true;
}
bool Salle::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Salle::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 17)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 17)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 17)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 17)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
