/**
 *
 *  Utilisateur.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace ProjetV1
{

class Utilisateur
{
  public:
    struct Cols
    {
        static const std::string _id_user;
        static const std::string _nom_user;
        static const std::string _prenom_user;
        static const std::string _login_user;
        static const std::string _hash_mdp;
        static const std::string _id_classe;
        static const std::string _role_user;
        static const std::string _uuid_badge;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Utilisateur(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Utilisateur(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Utilisateur(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Utilisateur() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id_user  */
    ///Get the value of the column id_user, returns the default value if the column is null
    const int32_t &getValueOfIdUser() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getIdUser() const noexcept;
    ///Set the value of the column id_user
    void setIdUser(const int32_t &pIdUser) noexcept;

    /**  For column nom_user  */
    ///Get the value of the column nom_user, returns the default value if the column is null
    const std::string &getValueOfNomUser() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getNomUser() const noexcept;
    ///Set the value of the column nom_user
    void setNomUser(const std::string &pNomUser) noexcept;
    void setNomUser(std::string &&pNomUser) noexcept;

    /**  For column prenom_user  */
    ///Get the value of the column prenom_user, returns the default value if the column is null
    const std::string &getValueOfPrenomUser() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPrenomUser() const noexcept;
    ///Set the value of the column prenom_user
    void setPrenomUser(const std::string &pPrenomUser) noexcept;
    void setPrenomUser(std::string &&pPrenomUser) noexcept;

    /**  For column login_user  */
    ///Get the value of the column login_user, returns the default value if the column is null
    const std::string &getValueOfLoginUser() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLoginUser() const noexcept;
    ///Set the value of the column login_user
    void setLoginUser(const std::string &pLoginUser) noexcept;
    void setLoginUser(std::string &&pLoginUser) noexcept;

    /**  For column hash_mdp  */
    ///Get the value of the column hash_mdp, returns the default value if the column is null
    const std::string &getValueOfHashMdp() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getHashMdp() const noexcept;
    ///Set the value of the column hash_mdp
    void setHashMdp(const std::string &pHashMdp) noexcept;
    void setHashMdp(std::string &&pHashMdp) noexcept;

    /**  For column id_classe  */
    ///Get the value of the column id_classe, returns the default value if the column is null
    const int32_t &getValueOfIdClasse() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getIdClasse() const noexcept;
    ///Set the value of the column id_classe
    void setIdClasse(const int32_t &pIdClasse) noexcept;
    void setIdClasseToNull() noexcept;

    /**  For column role_user  */
    ///Get the value of the column role_user, returns the default value if the column is null
    const std::string &getValueOfRoleUser() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRoleUser() const noexcept;
    ///Set the value of the column role_user
    void setRoleUser(const std::string &pRoleUser) noexcept;
    void setRoleUser(std::string &&pRoleUser) noexcept;

    /**  For column uuid_badge  */
    ///Get the value of the column uuid_badge, returns the default value if the column is null
    const std::string &getValueOfUuidBadge() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUuidBadge() const noexcept;
    ///Set the value of the column uuid_badge
    void setUuidBadge(const std::string &pUuidBadge) noexcept;
    void setUuidBadge(std::string &&pUuidBadge) noexcept;
    void setUuidBadgeToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 8;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Utilisateur>;
    friend drogon::orm::BaseBuilder<Utilisateur, true, true>;
    friend drogon::orm::BaseBuilder<Utilisateur, true, false>;
    friend drogon::orm::BaseBuilder<Utilisateur, false, true>;
    friend drogon::orm::BaseBuilder<Utilisateur, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Utilisateur>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> idUser_;
    std::shared_ptr<std::string> nomUser_;
    std::shared_ptr<std::string> prenomUser_;
    std::shared_ptr<std::string> loginUser_;
    std::shared_ptr<std::string> hashMdp_;
    std::shared_ptr<int32_t> idClasse_;
    std::shared_ptr<std::string> roleUser_;
    std::shared_ptr<std::string> uuidBadge_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[8]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id_user = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id_user = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id_user,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "nom_user,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "prenom_user,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "login_user,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "hash_mdp,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "id_classe,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "role_user,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "uuid_badge,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace ProjetV1
} // namespace drogon_model
