/**
 *
 *  Utilisateur.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Utilisateur.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::ProjetV1;

const std::string Utilisateur::Cols::_uuid_user = "\"uuid_user\"";
const std::string Utilisateur::Cols::_nom_user = "\"nom_user\"";
const std::string Utilisateur::Cols::_prenom_user = "\"prenom_user\"";
const std::string Utilisateur::Cols::_login_user = "\"login_user\"";
const std::string Utilisateur::Cols::_hash_mdp = "\"hash_mdp\"";
const std::string Utilisateur::Cols::_classe_user = "\"classe_user\"";
const std::string Utilisateur::Cols::_role_user = "\"role_user\"";
const std::string Utilisateur::Cols::_uuid_badge = "\"uuid_badge\"";
const std::string Utilisateur::primaryKeyName = "uuid_user";
const bool Utilisateur::hasPrimaryKey = true;
const std::string Utilisateur::tableName = "\"utilisateur\"";

const std::vector<typename Utilisateur::MetaData> Utilisateur::metaData_={
{"uuid_user","std::string","uuid",0,0,1,1},
{"nom_user","std::string","character varying",50,0,0,1},
{"prenom_user","std::string","character varying",50,0,0,1},
{"login_user","std::string","character varying",60,0,0,1},
{"hash_mdp","std::string","character varying",255,0,0,1},
{"classe_user","std::string","character varying",20,0,0,0},
{"role_user","std::string","character",0,0,0,1},
{"uuid_badge","int32_t","integer",4,0,0,0}
};
const std::string &Utilisateur::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Utilisateur::Utilisateur(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(r["uuid_user"].as<std::string>());
        }
        if(!r["nom_user"].isNull())
        {
            nomUser_=std::make_shared<std::string>(r["nom_user"].as<std::string>());
        }
        if(!r["prenom_user"].isNull())
        {
            prenomUser_=std::make_shared<std::string>(r["prenom_user"].as<std::string>());
        }
        if(!r["login_user"].isNull())
        {
            loginUser_=std::make_shared<std::string>(r["login_user"].as<std::string>());
        }
        if(!r["hash_mdp"].isNull())
        {
            hashMdp_=std::make_shared<std::string>(r["hash_mdp"].as<std::string>());
        }
        if(!r["classe_user"].isNull())
        {
            classeUser_=std::make_shared<std::string>(r["classe_user"].as<std::string>());
        }
        if(!r["role_user"].isNull())
        {
            roleUser_=std::make_shared<std::string>(r["role_user"].as<std::string>());
        }
        if(!r["uuid_badge"].isNull())
        {
            uuidBadge_=std::make_shared<int32_t>(r["uuid_badge"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            uuidUser_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            nomUser_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            prenomUser_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            loginUser_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            hashMdp_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            classeUser_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            roleUser_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            uuidBadge_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Utilisateur::Utilisateur(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            nomUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            prenomUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            loginUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            hashMdp_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            classeUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            roleUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            uuidBadge_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
}

Utilisateur::Utilisateur(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("uuid_user"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson["uuid_user"].asString());
        }
    }
    if(pJson.isMember("nom_user"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["nom_user"].isNull())
        {
            nomUser_=std::make_shared<std::string>(pJson["nom_user"].asString());
        }
    }
    if(pJson.isMember("prenom_user"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["prenom_user"].isNull())
        {
            prenomUser_=std::make_shared<std::string>(pJson["prenom_user"].asString());
        }
    }
    if(pJson.isMember("login_user"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["login_user"].isNull())
        {
            loginUser_=std::make_shared<std::string>(pJson["login_user"].asString());
        }
    }
    if(pJson.isMember("hash_mdp"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["hash_mdp"].isNull())
        {
            hashMdp_=std::make_shared<std::string>(pJson["hash_mdp"].asString());
        }
    }
    if(pJson.isMember("classe_user"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["classe_user"].isNull())
        {
            classeUser_=std::make_shared<std::string>(pJson["classe_user"].asString());
        }
    }
    if(pJson.isMember("role_user"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["role_user"].isNull())
        {
            roleUser_=std::make_shared<std::string>(pJson["role_user"].asString());
        }
    }
    if(pJson.isMember("uuid_badge"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["uuid_badge"].isNull())
        {
            uuidBadge_=std::make_shared<int32_t>((int32_t)pJson["uuid_badge"].asInt64());
        }
    }
}

void Utilisateur::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            nomUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            prenomUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            loginUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            hashMdp_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            classeUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            roleUser_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            uuidBadge_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
}

void Utilisateur::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("uuid_user"))
    {
        if(!pJson["uuid_user"].isNull())
        {
            uuidUser_=std::make_shared<std::string>(pJson["uuid_user"].asString());
        }
    }
    if(pJson.isMember("nom_user"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["nom_user"].isNull())
        {
            nomUser_=std::make_shared<std::string>(pJson["nom_user"].asString());
        }
    }
    if(pJson.isMember("prenom_user"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["prenom_user"].isNull())
        {
            prenomUser_=std::make_shared<std::string>(pJson["prenom_user"].asString());
        }
    }
    if(pJson.isMember("login_user"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["login_user"].isNull())
        {
            loginUser_=std::make_shared<std::string>(pJson["login_user"].asString());
        }
    }
    if(pJson.isMember("hash_mdp"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["hash_mdp"].isNull())
        {
            hashMdp_=std::make_shared<std::string>(pJson["hash_mdp"].asString());
        }
    }
    if(pJson.isMember("classe_user"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["classe_user"].isNull())
        {
            classeUser_=std::make_shared<std::string>(pJson["classe_user"].asString());
        }
    }
    if(pJson.isMember("role_user"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["role_user"].isNull())
        {
            roleUser_=std::make_shared<std::string>(pJson["role_user"].asString());
        }
    }
    if(pJson.isMember("uuid_badge"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["uuid_badge"].isNull())
        {
            uuidBadge_=std::make_shared<int32_t>((int32_t)pJson["uuid_badge"].asInt64());
        }
    }
}

const std::string &Utilisateur::getValueOfUuidUser() const noexcept
{
    static const std::string defaultValue = std::string();
    if(uuidUser_)
        return *uuidUser_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Utilisateur::getUuidUser() const noexcept
{
    return uuidUser_;
}
void Utilisateur::setUuidUser(const std::string &pUuidUser) noexcept
{
    uuidUser_ = std::make_shared<std::string>(pUuidUser);
    dirtyFlag_[0] = true;
}
void Utilisateur::setUuidUser(std::string &&pUuidUser) noexcept
{
    uuidUser_ = std::make_shared<std::string>(std::move(pUuidUser));
    dirtyFlag_[0] = true;
}
const typename Utilisateur::PrimaryKeyType & Utilisateur::getPrimaryKey() const
{
    assert(uuidUser_);
    return *uuidUser_;
}

const std::string &Utilisateur::getValueOfNomUser() const noexcept
{
    static const std::string defaultValue = std::string();
    if(nomUser_)
        return *nomUser_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Utilisateur::getNomUser() const noexcept
{
    return nomUser_;
}
void Utilisateur::setNomUser(const std::string &pNomUser) noexcept
{
    nomUser_ = std::make_shared<std::string>(pNomUser);
    dirtyFlag_[1] = true;
}
void Utilisateur::setNomUser(std::string &&pNomUser) noexcept
{
    nomUser_ = std::make_shared<std::string>(std::move(pNomUser));
    dirtyFlag_[1] = true;
}

const std::string &Utilisateur::getValueOfPrenomUser() const noexcept
{
    static const std::string defaultValue = std::string();
    if(prenomUser_)
        return *prenomUser_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Utilisateur::getPrenomUser() const noexcept
{
    return prenomUser_;
}
void Utilisateur::setPrenomUser(const std::string &pPrenomUser) noexcept
{
    prenomUser_ = std::make_shared<std::string>(pPrenomUser);
    dirtyFlag_[2] = true;
}
void Utilisateur::setPrenomUser(std::string &&pPrenomUser) noexcept
{
    prenomUser_ = std::make_shared<std::string>(std::move(pPrenomUser));
    dirtyFlag_[2] = true;
}

const std::string &Utilisateur::getValueOfLoginUser() const noexcept
{
    static const std::string defaultValue = std::string();
    if(loginUser_)
        return *loginUser_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Utilisateur::getLoginUser() const noexcept
{
    return loginUser_;
}
void Utilisateur::setLoginUser(const std::string &pLoginUser) noexcept
{
    loginUser_ = std::make_shared<std::string>(pLoginUser);
    dirtyFlag_[3] = true;
}
void Utilisateur::setLoginUser(std::string &&pLoginUser) noexcept
{
    loginUser_ = std::make_shared<std::string>(std::move(pLoginUser));
    dirtyFlag_[3] = true;
}

const std::string &Utilisateur::getValueOfHashMdp() const noexcept
{
    static const std::string defaultValue = std::string();
    if(hashMdp_)
        return *hashMdp_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Utilisateur::getHashMdp() const noexcept
{
    return hashMdp_;
}
void Utilisateur::setHashMdp(const std::string &pHashMdp) noexcept
{
    hashMdp_ = std::make_shared<std::string>(pHashMdp);
    dirtyFlag_[4] = true;
}
void Utilisateur::setHashMdp(std::string &&pHashMdp) noexcept
{
    hashMdp_ = std::make_shared<std::string>(std::move(pHashMdp));
    dirtyFlag_[4] = true;
}

const std::string &Utilisateur::getValueOfClasseUser() const noexcept
{
    static const std::string defaultValue = std::string();
    if(classeUser_)
        return *classeUser_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Utilisateur::getClasseUser() const noexcept
{
    return classeUser_;
}
void Utilisateur::setClasseUser(const std::string &pClasseUser) noexcept
{
    classeUser_ = std::make_shared<std::string>(pClasseUser);
    dirtyFlag_[5] = true;
}
void Utilisateur::setClasseUser(std::string &&pClasseUser) noexcept
{
    classeUser_ = std::make_shared<std::string>(std::move(pClasseUser));
    dirtyFlag_[5] = true;
}
void Utilisateur::setClasseUserToNull() noexcept
{
    classeUser_.reset();
    dirtyFlag_[5] = true;
}

const std::string &Utilisateur::getValueOfRoleUser() const noexcept
{
    static const std::string defaultValue = std::string();
    if(roleUser_)
        return *roleUser_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Utilisateur::getRoleUser() const noexcept
{
    return roleUser_;
}
void Utilisateur::setRoleUser(const std::string &pRoleUser) noexcept
{
    roleUser_ = std::make_shared<std::string>(pRoleUser);
    dirtyFlag_[6] = true;
}
void Utilisateur::setRoleUser(std::string &&pRoleUser) noexcept
{
    roleUser_ = std::make_shared<std::string>(std::move(pRoleUser));
    dirtyFlag_[6] = true;
}

const int32_t &Utilisateur::getValueOfUuidBadge() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(uuidBadge_)
        return *uuidBadge_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Utilisateur::getUuidBadge() const noexcept
{
    return uuidBadge_;
}
void Utilisateur::setUuidBadge(const int32_t &pUuidBadge) noexcept
{
    uuidBadge_ = std::make_shared<int32_t>(pUuidBadge);
    dirtyFlag_[7] = true;
}
void Utilisateur::setUuidBadgeToNull() noexcept
{
    uuidBadge_.reset();
    dirtyFlag_[7] = true;
}

void Utilisateur::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Utilisateur::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "uuid_user",
        "nom_user",
        "prenom_user",
        "login_user",
        "hash_mdp",
        "classe_user",
        "role_user",
        "uuid_badge"
    };
    return inCols;
}

void Utilisateur::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUuidUser())
        {
            binder << getValueOfUuidUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getNomUser())
        {
            binder << getValueOfNomUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPrenomUser())
        {
            binder << getValueOfPrenomUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLoginUser())
        {
            binder << getValueOfLoginUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getHashMdp())
        {
            binder << getValueOfHashMdp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getClasseUser())
        {
            binder << getValueOfClasseUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getRoleUser())
        {
            binder << getValueOfRoleUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getUuidBadge())
        {
            binder << getValueOfUuidBadge();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Utilisateur::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void Utilisateur::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUuidUser())
        {
            binder << getValueOfUuidUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getNomUser())
        {
            binder << getValueOfNomUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPrenomUser())
        {
            binder << getValueOfPrenomUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLoginUser())
        {
            binder << getValueOfLoginUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getHashMdp())
        {
            binder << getValueOfHashMdp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getClasseUser())
        {
            binder << getValueOfClasseUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getRoleUser())
        {
            binder << getValueOfRoleUser();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getUuidBadge())
        {
            binder << getValueOfUuidBadge();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Utilisateur::toJson() const
{
    Json::Value ret;
    if(getUuidUser())
    {
        ret["uuid_user"]=getValueOfUuidUser();
    }
    else
    {
        ret["uuid_user"]=Json::Value();
    }
    if(getNomUser())
    {
        ret["nom_user"]=getValueOfNomUser();
    }
    else
    {
        ret["nom_user"]=Json::Value();
    }
    if(getPrenomUser())
    {
        ret["prenom_user"]=getValueOfPrenomUser();
    }
    else
    {
        ret["prenom_user"]=Json::Value();
    }
    if(getLoginUser())
    {
        ret["login_user"]=getValueOfLoginUser();
    }
    else
    {
        ret["login_user"]=Json::Value();
    }
    if(getHashMdp())
    {
        ret["hash_mdp"]=getValueOfHashMdp();
    }
    else
    {
        ret["hash_mdp"]=Json::Value();
    }
    if(getClasseUser())
    {
        ret["classe_user"]=getValueOfClasseUser();
    }
    else
    {
        ret["classe_user"]=Json::Value();
    }
    if(getRoleUser())
    {
        ret["role_user"]=getValueOfRoleUser();
    }
    else
    {
        ret["role_user"]=Json::Value();
    }
    if(getUuidBadge())
    {
        ret["uuid_badge"]=getValueOfUuidBadge();
    }
    else
    {
        ret["uuid_badge"]=Json::Value();
    }
    return ret;
}

std::string Utilisateur::toString() const
{
    return toJson().toStyledString();
}

Json::Value Utilisateur::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getUuidUser())
            {
                ret[pMasqueradingVector[0]]=getValueOfUuidUser();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getNomUser())
            {
                ret[pMasqueradingVector[1]]=getValueOfNomUser();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPrenomUser())
            {
                ret[pMasqueradingVector[2]]=getValueOfPrenomUser();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getLoginUser())
            {
                ret[pMasqueradingVector[3]]=getValueOfLoginUser();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getHashMdp())
            {
                ret[pMasqueradingVector[4]]=getValueOfHashMdp();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getClasseUser())
            {
                ret[pMasqueradingVector[5]]=getValueOfClasseUser();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getRoleUser())
            {
                ret[pMasqueradingVector[6]]=getValueOfRoleUser();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getUuidBadge())
            {
                ret[pMasqueradingVector[7]]=getValueOfUuidBadge();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getUuidUser())
    {
        ret["uuid_user"]=getValueOfUuidUser();
    }
    else
    {
        ret["uuid_user"]=Json::Value();
    }
    if(getNomUser())
    {
        ret["nom_user"]=getValueOfNomUser();
    }
    else
    {
        ret["nom_user"]=Json::Value();
    }
    if(getPrenomUser())
    {
        ret["prenom_user"]=getValueOfPrenomUser();
    }
    else
    {
        ret["prenom_user"]=Json::Value();
    }
    if(getLoginUser())
    {
        ret["login_user"]=getValueOfLoginUser();
    }
    else
    {
        ret["login_user"]=Json::Value();
    }
    if(getHashMdp())
    {
        ret["hash_mdp"]=getValueOfHashMdp();
    }
    else
    {
        ret["hash_mdp"]=Json::Value();
    }
    if(getClasseUser())
    {
        ret["classe_user"]=getValueOfClasseUser();
    }
    else
    {
        ret["classe_user"]=Json::Value();
    }
    if(getRoleUser())
    {
        ret["role_user"]=getValueOfRoleUser();
    }
    else
    {
        ret["role_user"]=Json::Value();
    }
    if(getUuidBadge())
    {
        ret["uuid_badge"]=getValueOfUuidBadge();
    }
    else
    {
        ret["uuid_badge"]=Json::Value();
    }
    return ret;
}

bool Utilisateur::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("uuid_user"))
    {
        if(!validJsonOfField(0, "uuid_user", pJson["uuid_user"], err, true))
            return false;
    }
    else
    {
        err="The uuid_user column cannot be null";
        return false;
    }
    if(pJson.isMember("nom_user"))
    {
        if(!validJsonOfField(1, "nom_user", pJson["nom_user"], err, true))
            return false;
    }
    else
    {
        err="The nom_user column cannot be null";
        return false;
    }
    if(pJson.isMember("prenom_user"))
    {
        if(!validJsonOfField(2, "prenom_user", pJson["prenom_user"], err, true))
            return false;
    }
    else
    {
        err="The prenom_user column cannot be null";
        return false;
    }
    if(pJson.isMember("login_user"))
    {
        if(!validJsonOfField(3, "login_user", pJson["login_user"], err, true))
            return false;
    }
    else
    {
        err="The login_user column cannot be null";
        return false;
    }
    if(pJson.isMember("hash_mdp"))
    {
        if(!validJsonOfField(4, "hash_mdp", pJson["hash_mdp"], err, true))
            return false;
    }
    else
    {
        err="The hash_mdp column cannot be null";
        return false;
    }
    if(pJson.isMember("classe_user"))
    {
        if(!validJsonOfField(5, "classe_user", pJson["classe_user"], err, true))
            return false;
    }
    if(pJson.isMember("role_user"))
    {
        if(!validJsonOfField(6, "role_user", pJson["role_user"], err, true))
            return false;
    }
    else
    {
        err="The role_user column cannot be null";
        return false;
    }
    if(pJson.isMember("uuid_badge"))
    {
        if(!validJsonOfField(7, "uuid_badge", pJson["uuid_badge"], err, true))
            return false;
    }
    return true;
}
bool Utilisateur::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Utilisateur::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("uuid_user"))
    {
        if(!validJsonOfField(0, "uuid_user", pJson["uuid_user"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("nom_user"))
    {
        if(!validJsonOfField(1, "nom_user", pJson["nom_user"], err, false))
            return false;
    }
    if(pJson.isMember("prenom_user"))
    {
        if(!validJsonOfField(2, "prenom_user", pJson["prenom_user"], err, false))
            return false;
    }
    if(pJson.isMember("login_user"))
    {
        if(!validJsonOfField(3, "login_user", pJson["login_user"], err, false))
            return false;
    }
    if(pJson.isMember("hash_mdp"))
    {
        if(!validJsonOfField(4, "hash_mdp", pJson["hash_mdp"], err, false))
            return false;
    }
    if(pJson.isMember("classe_user"))
    {
        if(!validJsonOfField(5, "classe_user", pJson["classe_user"], err, false))
            return false;
    }
    if(pJson.isMember("role_user"))
    {
        if(!validJsonOfField(6, "role_user", pJson["role_user"], err, false))
            return false;
    }
    if(pJson.isMember("uuid_badge"))
    {
        if(!validJsonOfField(7, "uuid_badge", pJson["uuid_badge"], err, false))
            return false;
    }
    return true;
}
bool Utilisateur::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Utilisateur::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 60)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 60)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
